### ISSUE TITLE
Any plan for supporting AdBlocker?

### ISSUE THREAD

**Issue by MohamadBayz** [JingMatrix/ChromeXt#10]
Is there any future plan for implementing AdBlocker? I think you wrote something about AdAway when first release was published.

**Comment by JingMatrix** [comment]
Well, just use AdAway. I am using it, it works well.
I was trying to make Chrome work well with AdAway, so far it is good.

**Comment by MohamadBayz** [comment]
But beside all time running process of adaway and battery consuming, can you add a built-in AdBlocker to Google chrome like bromite?so it can just block ads inside google chrome, Just a suggestion

**Comment by JingMatrix** [comment]
To be honest, it is not easy.
So far, I can only block all user navigations, but not those backend connections. This is not useful. 

I might find methods later.

**Comment by JingMatrix** [comment]
There is no chance to implement an Adblocker. The recommanded way is using a proxy or AdAdway.

**Comment by MohamadBayz** [comment]
Sad to hear that anyway thanks for trying

**Comment by JingMatrix** [comment]
It might be possible to add a uBlock origin cosmetic Adblocker, since it could be run as purely a userscript.
This will be added to the dev plan.

**Comment by JingMatrix** [comment]
Done in 5261148b7c560fcaf51b601b2b4abf4c6a24bad1.

**Comment by MohamadBayz** [comment]
Great News, you have done a great job! 
It's working good although it has some bugs but I'm investigating. Btw is it possible for us to add custom cosmetic filter list?

**Comment by JingMatrix** [comment]
Nice, if you find bugs, please reqport them in new issues.

Yes, see README.md, you can add filters in the Resources panel, there is an `add` icon.
