### ISSUE TITLE
脚本未正确加载

### ISSUE THREAD

**Issue by WhiteSevs** [JingMatrix/ChromeXt#101]
发现使用`@require`库时，该库并不是注册全局变量，而是局部变量
类似
```javascript
const localVariable = {};
```
调试发现，并不是把库拼接在代码上面

**Comment by JingMatrix** [comment]
Please offer an example for the bug you are describing.
The variables by `@require` are finally properties of the global window object. But if you don't have `unsafeWindow`, you cannot access to the global `window` object.

**Comment by WhiteSevs** [comment]
主代码
```js
// ==UserScript==
// @name         测试
// @version      0.1
// @author       WhiteSevs
// @match        *://*/*
// @grant        GM_setValue
// @grant        GM_getValue
// @run-at       document-start
// @require      https://greasyfork.org/scripts/452322-js-watermark/code/js-watermark.js?version=1165991
// ==/UserScript==
(function(){
   console.log(Watermark);
})
```

js-Watermark这个库的3月份版本是以
```js
let Watermark = function()
```
创建的局部变量，在TamperMonkey中可以正确加载，因为它是把库的代码插入在上面

**Comment by JingMatrix** [comment]
Were you using the lastest `ChromeXt` from GitHub Actions?
This bug is already given in the issues #97 , and fixed now. But the fixing commits are not released yet.

**Comment by WhiteSevs** [comment]
并不是，使用的是上周的`3.7.0`的模块，我试下最新的看看

**Comment by JingMatrix** [comment]
Duplication of #97
