### ISSUE TITLE
`window` object is not the global one even if `unsafeWindow` is granted

### ISSUE THREAD

**Issue by WhiteSevs** [JingMatrix/ChromeXt#103]
`https://greasyfork.org/zh-CN/scripts/401359-mt%E8%AE%BA%E5%9D%9B`
1. 该脚本的库加上主代码加起来有好几万行代码，进行重新安装的时候，该脚本的主代码会被截断，导致脚本未正常运行。
2. 在某些时刻，由于`@run-at document-start`，脚本的`jQuery库`会执行失败，可能是时刻太早了。
3. 想问如果进行覆盖安装，脚本之前使用`GM_setValue`存储的数据会保留吗？
4. `GM_xmlhttpRequest`似乎是使用`fetch`实现的，导致了一个问题就是无法进行跨域请求数据

**Comment by JingMatrix** [comment]
先简单回复一下
3. 会覆盖
4. fetch 失败了会转而使用 Java

**Comment by JingMatrix** [comment]
The support for your provided script is fixed.
As for your point 2, if you have the need to keep the previous srcipt storge, I can add an option for that.
Is that what you want? Please open a new issue if that is the case.

**Comment by WhiteSevs** [comment]
保留数据很有需要，因为数据里会有脚本的设置，覆盖安装会导致这些数据丢失。关于第4点，有待测试验证一下，明天会来提个issue
