### ISSUE TITLE
Whale browser update broke it 

### ISSUE THREAD

**Issue by Leekawaii666** [JingMatrix/ChromeXt#107]
Hello I'm sorry to annoy you but it seems the new whale browser update [Apkmirror link](https://www.apkmirror.com/apk/naver-corp/naver-whale-browser/naver-whale-browser-3-0-1-2-release/) has broken chromext in someway. 

Please let me know if a fix can or can't be made as I will downgrade my browser if I need to.

**Comment by JingMatrix** [comment]
Don't worry, it is fixed now. Please install it from GitHub Actions.
It might break the old versions of `Whale`, but I cannot downgrade `Whale` from `Google Play` to check that.
It will be helpful of you if you can test whether the new ChromeXt works for old versions as well.
