### ISSUE TITLE
eruda not work in webview

### ISSUE THREAD

**Issue by WhiteSevs** [JingMatrix/ChromeXt#108]
![image](https://github.com/JingMatrix/ChromeXt/assets/50544447/90046d55-73f9-4099-a2cc-3c14dbc24b69)
![image](https://github.com/JingMatrix/ChromeXt/assets/50544447/f66cc3f1-ff0a-45a4-84bf-74d56df31477)

**Comment by JingMatrix** [comment]
It seems to be a bug of `LSPosed`. Please try the latest fix I made: 281daa191d080b6ee980afbd3903407fc3c12ccb.
If it is still not working, tell me which browser you are using.

**Comment by WhiteSevs** [comment]
啊，应该是我使用的原版的lspatch打包的问题用你的![https://github.com/JingMatrix/LSPatch/actions/runs/5846780343](https://github.com/JingMatrix/LSPatch/actions/runs/5846780343)重新打包后就可以了
