### ISSUE TITLE
some error may be with GM_xmlhttpRequest HEAD method

### ISSUE THREAD

**Issue by WhiteSevs** [JingMatrix/ChromeXt#109]
该请求是`method`为`HEAD`的方法
脚本地址[https://greasyfork.org/zh-CN/scripts/445489-网盘链接识别](https://greasyfork.org/zh-CN/scripts/445489-网盘链接识别)
![image](https://github.com/JingMatrix/ChromeXt/assets/50544447/7c3aa8a1-ac7d-4232-aa45-541e0367e284)

**Comment by JingMatrix** [comment]
How to triger the floating button manually?  It only showed once in my device, but the error didn't show.
Could you please add an menu item using `GM_registerMenuCommand` (for debug purpose at least) to trigger it x?

**Comment by WhiteSevs** [comment]
安装该脚本后，在这个页面就会识别到网盘链接(底部)，会自动出现悬浮按钮，通过`双击`打开设置菜单
打开`蓝奏云`选项开启`单/多文件直链获取`
![image](https://github.com/JingMatrix/ChromeXt/assets/50544447/2cbd7c9c-40d1-4709-852f-4b80a56ebb9f)
关闭弹窗后，`单击`悬浮按钮打开弹窗，点击识别到的链接，就会自动获取`直链`

**Comment by WhiteSevs** [comment]
> How to triger the floating button manually? It only showed once in my device, but the error didn't show. Could you please add an menu item using `GM_registerMenuCommand` (for debug purpose at least) to trigger it?

或者使用下面的代码手动触发一下？
```js
window.dispatchEvent(new Event("load"))
```

**Comment by JingMatrix** [comment]
Okay, I see it. Please use `@run-at document-end` instead of `@run-at document-body` .
Now I can see the floating button, but there is no parsing error.
Could you give steps to reproduce it (including which browsers your are testing)? Maybe it is not reproducible each time.

**Comment by WhiteSevs** [comment]
https://github.com/JingMatrix/ChromeXt/assets/50544447/89fb8b5a-e30d-496e-abfd-46ab08bdbd05
