### ISSUE TITLE
Cosmetic Filter doesn't let other script run

### ISSUE THREAD

**Issue by MohamadBayz** [JingMatrix/ChromeXt#11]
I found a bug, if you delete an element with the cosmetic filter and refresh the webpage it will block other script from running on that website

**Comment by JingMatrix** [comment]
I see, will fix soon.

**Comment by JingMatrix** [comment]
This is fixed in 495c15b10a4e00a416dcff9f7aefc6f1ab87855a. Please install the new cosmetic script.

However, due to a front end bug just found in 7cb507590fb2105d938fb59dbaac60c5ded37f6a, if your script still won't run, you have to reinstalled that script as well.
