### ISSUE TITLE
GM_deleteValue存在问题

### ISSUE THREAD

**Issue by WhiteSevs** [JingMatrix/ChromeXt#110]
测试`GM_deleteValue`无法删除

![image](https://github.com/JingMatrix/ChromeXt/assets/50544447/e2b46f82-29c9-4448-9de8-3b30173ad0db)

**Comment by WhiteSevs** [comment]
应该是这段有问题
```js
deleteProperty(target, key) {
      delete target.key; // 目标错误
      this.sync({ key });
},
```
正确的👇
deleteProperty(target, key) {
      delete target[key]; // 目标错误
      this.sync({ key });
},

**Comment by JingMatrix** [comment]
My bad, thanks for spotting it.
