### ISSUE TITLE
Medias element in Google Websites not interactable

### ISSUE THREAD

**Issue by Leekawaii666** [JingMatrix/ChromeXt#111]
I have confirmed this bug in whale browser and chrome. 
I cannot click on images in Google images. Deleting all scripts doesn't solve said issue. 
![QuickScreencapture_20230916-210601](https://github.com/JingMatrix/ChromeXt/assets/100771281/4c478f89-dfe2-485f-8aeb-f2c66c46c0c2)
This also happens in some sites. 

Thank you so much for all your hard work.

**Comment by JingMatrix** [comment]
I have no ideas of what is happening, it is indeed wired.
