### ISSUE TITLE
install script event not trigger

### ISSUE THREAD

**Issue by WhiteSevs** [JingMatrix/ChromeXt#113]
https://github.com/JingMatrix/ChromeXt/assets/50544447/20e78e78-b4c4-4673-b06a-382c059c94d5

可以像这样
https://github.com/WhiteSevs/TamperMonkeyScript/blob/610351d6c8c762643e31c7040164f75ca8b9072f/%E5%BA%93/DOMUtils.js#L1070
添加`load`事件监听

**Comment by JingMatrix** [comment]
Sorry, I didn't understand, is there a UserScript failed to show the prompt?
Maybe it is an offline page.

**Comment by WhiteSevs** [comment]
是的，页面加载完毕，但是`DOMContentLoaded`并未触发，且这并不是脱机页面，这是greasyfork我上传的未公布的脚本

**Comment by JingMatrix** [comment]
Actually, the `editor.js` needs some kind of refactor to fix the issue #100, so I planned to fix your issue later.
But since you need it, I just pused a commit for it.
