### ISSUE TITLE
[Feature Request] "Enable reader mode manually" adapt to Kiwi Browser

### ISSUE THREAD

**Issue by chuwza** [JingMatrix/ChromeXt#117]
Hi, this feature doesn't work on Kiwi. Kiwi is a Chromium based browsers, and has the same look and feel as Chrome, an adaptation might be possible, could you please bring this feature to Kiwi?
![Screenshot_20230924-212158_Kiwi_Browser](https://github.com/JingMatrix/ChromeXt/assets/30049891/468b2fdf-6a16-4cc2-b639-56a438950c56)

**Comment by JingMatrix** [comment]
I didn't expect kiwi browser users will need `ChromeXt` one day since you can ask its maintainers to add this functionality.
Anyway, this is done now at your request.

**Comment by chuwza** [comment]
> I didn't expect kiwi browser users will need `ChromeXt` one day since you can ask its maintainers to add this functionality. Anyway, this is done now at your request.

Your "Enable reader mode manually" is very useful, so I need it even though I use Kiwi.

You're so efficient! Thank you very much👍
