### ISSUE TITLE
[Feature Request] "Enable reader mode manually" adapt to Chrome Tablet

### ISSUE THREAD

**Issue by chuwza** [JingMatrix/ChromeXt#118]
Hello, I found "Enable reader mode manually" feature didn't work in Chrome Tablet.

When Chrome is in tablet mode, the info bar disappears. This causes the kind of adaptation on the phone is no longer work on tablet.
![Screenshot_20230924-235809_Chrome~2](https://github.com/JingMatrix/ChromeXt/assets/30049891/1f92d079-a824-4a2e-a03e-bca25abaec63)

Sorry, I don't know how to make it work, maybe possibly by edit Toolbar shortcut?
![Screenshot_20230924-235527_Chrome](https://github.com/JingMatrix/ChromeXt/assets/30049891/3612356a-e4e0-4eb0-8b48-e56b53ec0fb7)

**Comment by JingMatrix** [comment]
I don't possess an Android tablet, so I don't know neither.
Is there a way to use Chrome in tablet mode for Andorid phone?

**Comment by chuwza** [comment]
> I don't possess an Android tablet, so I don't know neither. Is there a way to use Chrome in tablet mode for Andorid phone?

Yes, there is a way, and it's easy. Change the "Smallest width" in the "Developer options" to `600`, then open Chrome and it will be in tablet mode.
![IMG_20230925_072503](https://github.com/JingMatrix/ChromeXt/assets/30049891/4105be91-7c58-4acc-bd75-c9b2e8417556)

Regarding the implementation of this feature, perhaps you could insert "Reader mode" like you inserted "Eruda console", which might be a more general and simpler way to implement it?
![Screenshot_20230925-072322_Chrome~2](https://github.com/JingMatrix/ChromeXt/assets/30049891/83ecba05-d15d-4165-86b4-a2054ea65b76)

**Comment by JingMatrix** [comment]
I used `DPI` to check if current device is a tablet.
Please leave a message if this fix works for your devices.

**Comment by chuwza** [comment]
> I used `DPI` to check if current device is a tablet. Please leave a message if this fix works for your devices.

It works! Thank you very much!
![Screenshot_20230925-180823_Kiwi_Browser](https://github.com/JingMatrix/ChromeXt/assets/30049891/d90f31a2-e670-4117-b4c8-63af4b6426a5)

**Comment by chuwza** [comment]
> I used `DPI` to check if current device is a tablet. Please leave a message if this fix works for your devices.

Hello, This suddenly doesn't work😂. I don't know what's going on, but now I'm using Action's latest version of Chromext, and I can't activate the info bar on 117 Chrome and 116 Kiwi (I've cleared three app's data). I've tested it on both my tablet and my DPI 600 phone and it won't activate, is it just me? Is this my fault? Could you please test it?😂😭
![Screenshot_20230925-200047_Chrome](https://github.com/JingMatrix/ChromeXt/assets/30049891/3b0c8c2e-3816-470b-b09a-57018ed145e9)
![Screenshot_20230925-195509_Chrome](https://github.com/JingMatrix/ChromeXt/assets/30049891/b9819440-c56a-4994-bfd5-4a66490a9919)

**Comment by JingMatrix** [comment]
Don't worry, it is fixed now. I asked for your feedback since I was not sure whether `DPI` is reliable to detect a tablet.
Now it should work well with the `smallestScreenWidthDp` property.

**Comment by chuwza** [comment]
> Don't worry, it is fixed now. I asked for your feedback since I was not sure whether `DPI` is reliable to detect a tablet. Now it should work well with the `smallestScreenWidthDp` property.

Thank you very much👍, It works now
