### ISSUE TITLE
[Feature Request] "Developer options" adapt Kiwi Browser

### ISSUE THREAD

**Issue by chuwza** [JingMatrix/ChromeXt#119]
Hello, I use Kiwi Browser and want disable "Browser gesture navigation". But I find that no matter how I turn it on, it never works, when I close the option and re-enter the browser, the option opens again. This option compatible with Chrome and Edge, so maybe it's just not compatible with Kiwi.

I've also found that it's not just "Browser gesture navigation" option doesn't work, it's all the options don't respond when clicked on, such as GIF.
![kiwi bro](https://github.com/JingMatrix/ChromeXt/assets/30049891/4df4bf63-568d-41ae-bc9e-991f7da98931)

BTW, don't use Kiwi Browser version 116, the latest version has a well-defined bug that prevents you from turning on developer options. So I recommend using the previous version 112. (https://www.apkmirror.com/apk/geometry-ou/kiwi-browser-fast-quiet/kiwi-browser-fast-quiet-112-0-5615-137-release/)

**Comment by JingMatrix** [comment]
Thanks for reporting this bug.
This bug also presents in `bromite` due to a wrong commit in `ChromeXt v3.6`.

**Comment by chuwza** [comment]
> Thanks for reporting this bug. This bug also presents in `bromite` due to a wrong commit in `ChromeXt v3.6`.

Thank, I got it. Will you be fixing this bug in the near future?

**Comment by JingMatrix** [comment]
It is already fixed. Here is the github convention: when it shows
```
JingMatrix closed this as completed in 7902b50 1 hour ago
```
it means that this issue is fixed by the commit 7902b50.
If it is not working, please report it.

**Comment by chuwza** [comment]
> It is already fixed. Here is the github convention: when it shows
> 
> ```
> JingMatrix closed this as completed in 7902b50 1 hour ago
> ```
> 
> it means that this issue is fixed by the commit [7902b50](https://github.com/JingMatrix/ChromeXt/commit/7902b503a7a1dcea4a810e04cdddfe96e016ec55). If it is not working, please report it.

Okay, now I know it. And I tested it, it works fine : )
