### ISSUE TITLE
Dev tools blank space

### ISSUE THREAD

**Issue by MohamadBayz** [JingMatrix/ChromeXt#12]
If you open dev tools and start scrolling down of a webpage a blank space will appear under the dev tools as the one in the screenshot
![Screenshot_20221228-135316_Chrome](https://user-images.githubusercontent.com/63660736/209801401-ec7a8ba3-bba4-4a50-a226-81cf4d8dda8a.png)

**Comment by JingMatrix** [comment]
This sounds more like an issue of [eruda](https://github.com/liriliri/eruda).
Please report there if you want.

Pearsonally, I feel it is tolerable since usually it behaves well; so I didn't report it.
