### ISSUE TITLE
`Enable reader mode manually` for `Chrome Custom Tabs`

### ISSUE THREAD

**Issue by chuwza** [JingMatrix/ChromeXt#120]
Hi, sorry, not sure if so many Issues are bothering you. So thank you for your work.😀

I found a bug now, such is picture, "Enable reader mode manually" can works in normal web, but doesn't work in "Custom Tabs"
![Screenshot_20230925-202852_Chrome~2](https://github.com/JingMatrix/ChromeXt/assets/30049891/6203fb12-2489-4940-925a-26a688f7c1b4)

**Comment by JingMatrix** [comment]
That is an intentional design of `ChromeXt`.
Since you can use the `Open in Chrome` menu, I personally don't find the reason to replace the icon row menu.

**Comment by JingMatrix** [comment]
If I remeber it correctly, the modfication for custom tabs is slightly more difficult (which is part of the reason for this intentional design).
It takes some time to do that, but will be implemented soon.

**Comment by chuwza** [comment]
> If I remeber it correctly, the modfication for custom tabs is slightly more difficult (which is part of the reason for this intentional design). It takes some time to do that, but will be implemented soon.

OK, Thank you very much🥳

**Comment by JingMatrix** [comment]
Now this is implemented.
Keep in mind one rule: if you couldn't find the reader mode icon, it is because that you __never__ have opened the page menu once in the `Chrome`  application.

To keep `ChromeXt` less complicated, the above rule, though not perfect for user experience, won't be fixed for now.

**Comment by chuwza** [comment]
> Now this is implemented. Keep in mind one rule: if you couldn't find the reader mode icon, it is because that you **never** have opened the page menu once in the `Chrome` application.
> 
> To keep `ChromeXt` less complicated, the above rule, though not perfect for user experience, won't be fixed for now.

Hello, there may still be some problems with this feature, I clicked on the reader mode icon, but nothing happened.

https://github.com/JingMatrix/ChromeXt/assets/30049891/c85a3ba5-5a45-427a-91a1-c4b09206e989

**Comment by JingMatrix** [comment]
My bad, I forgot to setup the click listeners for it. Now it is fixed.
