### ISSUE TITLE
Samsung browser with 3.8 modified can no longer recognize the script, is opened in the form of text.

### ISSUE THREAD

**Issue by wowotaa** [JingMatrix/ChromeXt#123]
Would love to add script switches and menu options.

**Comment by JingMatrix** [comment]
Could not reproduce your issue. Please specify which scripts are not recognized.
Note: for each update, you need to fully restart your browser.

**Comment by wowotaa** [comment]
我用三星浏览器 beta23.0.0.34 版本， 集成 chrome Xt 模块建筑 所有脚本都不能正常识别

**Comment by JingMatrix** [comment]
If you find a way to reproduce this issue, I will re-open it.

**Comment by wowotaa** [comment]
我已经重现问题，是因为刚下载的脚本后缀带 user.js，我去掉.user 改为.js 可以正常打开。



发送自我的盖乐世



-------- 原始信息 --------
发件人： JingMatrix ***@***.***>
日期: 2023/10/4 下午4:46 (GMT+08:00)
收件人： JingMatrix/ChromeXt ***@***.***>
抄送： wowotaa ***@***.***>, Author ***@***.***>
主题： Re: [JingMatrix/ChromeXt] Samsung browser with 3.8 modified can no longer recognize the script, is opened in the form of text. (Issue #123)


If you find a way to reproduce this issue, I will re-open it.

―

**Comment by JingMatrix** [comment]
Note that, you can also install UserScript from the eruda info panel.
![Screenshot_20231004-121005](https://github.com/JingMatrix/ChromeXt/assets/24476093/60acfddf-6646-4501-996e-50d6670734d7)

**Comment by wowotaa** [comment]
这个功能一直没有找到怎么进去



发送自我的盖乐世



-------- 原始信息 --------
发件人： JingMatrix ***@***.***>
日期: 2023/10/4 下午6:15 (GMT+08:00)
收件人： JingMatrix/ChromeXt ***@***.***>
抄送： wowotaa ***@***.***>, Author ***@***.***>
主题： Re: [JingMatrix/ChromeXt] Samsung browser with 3.8 modified can no longer recognize the script, is opened in the form of text. (Issue #123)


Note that, you can also install UserScript from the eruda info panel.
[Screenshot_20231004-121005]<https://user-images.githubusercontent.com/24476093/272541235-60acfddf-6646-4501-996e-50d6670734d7.png>

―

**Comment by JingMatrix** [comment]
Here are the steps for Samsung browsers:
1. Long press on the screen (you may need to select some texts) to show the context menu
2. Click on `Eruda console` in the context menu
3. Click on `Info` in the first line of eruda console

**Comment by wowotaa** [comment]
[cid:storage_emulated_0_DCIM_Screenshots_Screenshot_20231004_190316_Samsung_Internet_Beta_jpg_1696417423925]



发送自我的盖乐世



-------- 原始信息 --------
发件人： JingMatrix ***@***.***>
日期: 2023/10/4 下午7:00 (GMT+08:00)
收件人： JingMatrix/ChromeXt ***@***.***>
抄送： wowotaa ***@***.***>, Author ***@***.***>
主题： Re: [JingMatrix/ChromeXt] Samsung browser with 3.8 modified can no longer recognize the script, is opened in the form of text. (Issue #123)


Here are the steps for Samsung browsers:

  1.  Long press on the screen (you may need to select some texts) to show the context menu
  2.  Click on Eruda console in the context menu
  3.  Click on Info in the first line of eruda console

―

**Comment by wowotaa** [comment]
没有找到该选项



发送自我的盖乐世



-------- 原始信息 --------
发件人： JingMatrix ***@***.***>
日期: 2023/10/4 下午7:00 (GMT+08:00)
收件人： JingMatrix/ChromeXt ***@***.***>
抄送： wowotaa ***@***.***>, Author ***@***.***>
主题： Re: [JingMatrix/ChromeXt] Samsung browser with 3.8 modified can no longer recognize the script, is opened in the form of text. (Issue #123)


Here are the steps for Samsung browsers:

  1.  Long press on the screen (you may need to select some texts) to show the context menu
  2.  Click on Eruda console in the context menu
  3.  Click on Info in the first line of eruda console

―
