### ISSUE TITLE
Request: Global UI for all selected browsers/apps/webviews

### ISSUE THREAD

**Issue by GreenDotBlue99** [JingMatrix/ChromeXt#127]
To manage functionality and scripts.

**Comment by JingMatrix** [comment]
Scripts are managed in the front end: https://jingmatrix.github.io/ChromeXt/

**Comment by GreenDotBlue99** [comment]
Yes, but also change functionality of ChromeXt
Webextension if you plan to add.

Anyway, nice app!

**Comment by JingMatrix** [comment]
> Yes, but also change functionality of ChromeXt Webextension if you plan to add.

You meant that you didn't want to do some settings through the `Developer options` menu?
They are meant for developer, so I think normally people don't need them. This makes the front-end lighter and cleaner.
