### ISSUE TITLE
Abnormally high CPU usage on script installtion page

### ISSUE THREAD

**Issue by 66Leo66** [JingMatrix/ChromeXt#129]
I'm using
- Vivaldi Browser 6.2.3110.143 (Stable channel) （64 Bit)
- ChromeXt Latest Github Actions Build
- Installing [KISS Translator](https://greasyfork.org/zh-CN/scripts/472840-kiss-translator) but this happens on other scripts and before clicking install

If I click install: the confirmation popup closes but script didn't get installed

If I click ask 30s later, browser become extremely laggy, editor is unusable and CPU goes 100%

![Screenshot_2023-10-28-16-02-14-925_com vivaldi browser](https://github.com/JingMatrix/ChromeXt/assets/33322229/21c723f2-4c6e-4bc3-86b2-1e75cb41303e)

**Comment by JingMatrix** [comment]
Thanks for reporting, I believe this is fixed now. At least, there is no problem for my device with 8G RAM. If not, please tell me.

The browser becomes laggy bacause you are installing a quite large script, where CPU are used to highlight the JavaScript syntax.

**Comment by 66Leo66** [comment]
Yes, I can confirm installtion is working. Thanks!
