### ISSUE TITLE
Add support for regular (non-split) apk file

### ISSUE THREAD

**Issue by inguna87** [JingMatrix/ChromeXt#13]
Hi, do you mind making it compatible with normal chrome apk file.
Because I use original non-split apk your module can't hook to it.
https://apkcombo.com/chrome/com.android.chrome/download/apk
![Screenshot_20221229-011750](https://user-images.githubusercontent.com/103364968/209891357-86879a19-392f-42a8-8f9f-3b39d92cf1a9.jpg)
[modules_2022-12-29T01:10:09.104.txt](https://github.com/JingMatrix/ChromeXt/files/10317162/modules_2022-12-29T01.10.09.104.txt)
Thanks a lot in advance and keep up the good work!

**Comment by JingMatrix** [comment]
Do you know coding for Android?
It would be good if you can help this project with the non-split part.
Currently the non-split apk has different smali mathod names, and one need to find them out.
The way to find them are written in the code comments, so it is not hard.

I am using the split one, it is inconvient for me to test.

**Comment by JingMatrix** [comment]
Now I have add support for the non-split version, please test it.
Normally, it should work well.
And if you find that it is not working, pasted the error logs from Xposed to this issue.

**Comment by inguna87** [comment]
Thank you for taking your time addressing this issue. Unfortunately, I am not a coder and I won't be able to help you with code. I can only test ready apks.
I downloaded new version from [here](https://github.com/JingMatrix/ChromeXt/actions/runs/3797880238) but the error is the same
java.lang.ClassNotFoundException: Didn't find class "org.chromium.chrome.browser.base.SplitChromeApplication".  Log is attached below. Thank you
[modules_2022-12-29T03:19:14.657.txt](https://github.com/JingMatrix/ChromeXt/files/10317448/modules_2022-12-29T03.19.14.657.txt)

**Comment by JingMatrix** [comment]
No I implement userscript support for the non-split version, but other features are not available so far.

**Comment by JingMatrix** [comment]
Almost fully-supported.

**Comment by inguna87** [comment]
Thank you! We are grateful for your hard work!
