### ISSUE TITLE
Install button disappears from menu?

### ISSUE THREAD

**Issue by xushet** [JingMatrix/ChromeXt#131]
![Screenshot_20231103-100402_Chrome.png](https://github.com/JingMatrix/ChromeXt/assets/34502902/83108c5c-8cf4-4fca-8c67-f67e5a1f5004)

After I modified the code, I could only wait 30 seconds for installation.

Android 13 AOSP

com.android.chrome 119.0.6045.66

**Comment by JingMatrix** [comment]
I cannot reproduce it. Could you fully restart your browser to see if this problem still happens?
It could simply be that you updated the browser with killing the process.

**Comment by xushet** [comment]
> I cannot reproduce it. Could you fully restart your browser to see if this problem still happens?
> It could simply be that you updated the browser with killing the process.

I'm in chrome://flags/#request-desktop-site-zoom. Maybe it's because the install button is covered. I suggest designing the button to the bottom of the menu so that it won't be covered no matter what chrome updates.

**Comment by JingMatrix** [comment]
Still cannot reproduce it. Did you try the lastest build from GitHub Action?

**Comment by xushet** [comment]
> Still cannot reproduce it. Did you try the lastest build from GitHub Action?

Install Android CI #599, the install button reappeared in the menu and it working
