### ISSUE TITLE
GM_cookie.set and GM_cookie.delete API are not functioning

### ISSUE THREAD

**Issue by cloudswave** [JingMatrix/ChromeXt#134]
The GM_cookie.list API is OK, but when I try to  invoke  GM_cookie.set and GM_cookie.delete APIs, they are  not functioning. Can you help me?
[The tampermonkey document ](https://www.tampermonkey.net/documentation.php?ext=dhdg##api:GM_cookie.set)
Example:
```
GM_cookie.set({
  url: 'https://example.com',
  name: 'name',
  value: 'value',
  domain: '.example.com',
  path: '/',
  secure: true,
  httpOnly: true,
  expirationDate: Math.floor(Date.now() / 1000) + (60 * 60 * 24 * 30) // Expires in 30 days
}, function(error) {
  if (error) {
    console.error(error);
  } else {
    console.log('Cookie set successfully.');
  }
});

GM_cookie.delete({ name: 'cookie_name' }, function(error) {
    if (error) {
        console.error(error);
    } else {
        console.log('Cookie deleted successfully');
    }
});
```

**Comment by JingMatrix** [comment]
The design principle is given in #115.
Please offer a whole script so that I may explain in more details.

**Comment by cloudswave** [comment]
> The design principle is given in #115. Please offer a whole script so that I may explain in more details.

Install the [test script](https://greasyfork.org/zh-CN/scripts/479512-cookiehelper),   then opening any webpage and it will display test buttons. 
Here is a  desktop edge Tampermonkey BETA invoke GM_cookie successfully screenshot.
![image](https://github.com/JingMatrix/ChromeXt/assets/5915548/344d9c26-e7ea-4b33-807b-403bb783551d)

**Comment by JingMatrix** [comment]
The problem was mainly that your script missed the `domain` parameter, which is now required by Chromium browsers.
Now this is fixed, as I add the default `domain` paremeter.

**Comment by cloudswave** [comment]
> The problem was mainly that your script missed the `domain` parameter, which is now required by Chromium browsers. Now this is fixed, as I add the default `domain` paremeter.
Verified, the problem has been fixed. Thanks
