### ISSUE TITLE
README.md Invalid link

### ISSUE THREAD

**Issue by green1052** [JingMatrix/ChromeXt#135]
https://github.com/JingMatrix/ChromeXt#contribute-to-this-project

[manager.vue](https://github.com/JingMatrix/viteblog/tree/master/components/ChromeXt/manager.vue) is invaild

**Comment by JingMatrix** [comment]
Okay, now I have make the repo [JingMatrix/viteblog](https://github.com/JingMatrix/viteblog) public again.
Please note that the repo `viteblog` is not open source and would be not be open source in the future.
Nevertheless, you are still welcome to contribute to the `manager.vue` UI components.
