### ISSUE TITLE
Console menu not showing for the Github Release version

### ISSUE THREAD

**Issue by Gul7333** [JingMatrix/ChromeXt#137]
I am beginner...
I have rooted phone and I have installed lsposed and 
I installed chromeXt... I can download user script....
I watched your video on YouTube.... Installed immersive translation user script,,,.it works....
But in my chrome side panel there is no eruda console or tools....which I really need...
Does I have to install eruda user script...
Doesn't ChromXt provide Dev tools...

Any help for enabling developer tools and console in chrome

**Comment by JingMatrix** [comment]
1. What is your browser version?
2.  Did you install ChromeXt from GitHub Actions?
3. You may provide a screen recording here for me to analyze the problem.

**Comment by Gul7333** [comment]
The chrome is latest
119.0.6045.163 (Official Build) (64-bit)
Mobile is Techno pova Ld7
Android 10

Here is link to video,,,you can see here user script can be installed on chrome but Dev tools and eruda is not showing
Link of screen recording 
https://drive.google.com/file/d/13XwrGtirLO6dze0NojvRnzyrLh874d_l/view?usp=drivesdk

**Comment by JingMatrix** [comment]
The second question is the most important one: did you install ChromeXt from **GitHub Action**?
If not, you should do that.

**Comment by Gul7333** [comment]
Yes I installed from here your repo

**Comment by JingMatrix** [comment]
This is the link of [GitHub Actions](https://github.com/JingMatrix/ChromeXt/actions/runs/6987875396). It is different from the one in GitHub Release, which is **out-of-date**.
Not installing from **GitHub Action** is the only possible reason why don't have the console menu showing.

**Comment by Gul7333** [comment]
How to download apk from GitHub action.... I opened it but there is no apk

**Comment by JingMatrix** [comment]
Scroll down that linked page, you will find the ``Artifacts`` panel, which provide an zipped apk. This is the [direct link](https://github.com/JingMatrix/ChromeXt/suites/18487258027/artifacts/1072626116).

**Comment by Gul7333** [comment]
If I have to manually build, which I can't as I started learning web development and I don't know apps building process....
If you could update you repo release...
That would help

**Comment by Gul7333** [comment]
Download zip file and install 

Ok.... thanks now it is working

**Comment by JingMatrix** [comment]
> Download zip file and install
> 
> Ok.... thanks now it is working

Yeah, it is at the 9:23 of the Youtube video.

**Comment by Gul7333** [comment]
Yes...I saw release apk on front page of repo...so I thought it is latest one ...bye the way thanks for support

**Comment by JingMatrix** [comment]
> Yes...I saw release apk on front page of repo...so I thought it is latest one ...bye the way thanks for support

You are welcome.
ChromeXt is always updating to fix bugs for supporting new versions of Chrome (and many other) browsers, the most convenient way to distribute APKs is hence using GitHub Actions, which builds the project for each new commit.
