### ISSUE TITLE
Is it possible to support Mi Browser?

### ISSUE THREAD

**Issue by Sostay** [JingMatrix/ChromeXt#138]
之前有一个支持的 后来没有维护了 
https://github.com/KYMirai/MiCode

**Comment by JingMatrix** [comment]
It seems hard to hook `Mi Browser` correctly. I didn't success for now.

**Comment by Sostay** [comment]
> It seems hard to hook `Mi Browser` correctly. I didn't success for now.

目前它还能工作，只是有一些小问题，如果能把核心功能合并到chromext就好了~
[
![Screenshot_2023-12-02-20-10-00-297_com android browser](https://github.com/JingMatrix/ChromeXt/assets/6897274/875b1fa8-b9bf-469a-86ff-284884f5b603)
](url)

**Comment by JingMatrix** [comment]
I have implemented basic UserScript functions for `Mi Browser`, though `eruda console` is not available yet.
I can only find the international version of `Mi Browser`. If you have the link to the China-only version browser, please provide it here.

You can try it out from [GitHub Actions #600](https://github.com/JingMatrix/ChromeXt/actions/runs/7073513618).

**Comment by JingMatrix** [comment]
I couldn't install your package.
But I guess it should work fine, please resport it if it is not working for you.
