### ISSUE TITLE
Open in chrome has disappeard

### ISSUE THREAD

**Issue by MohamadBayz** [JingMatrix/ChromeXt#14]
After enabling Developer Tools "Open In Chrome" Section has disappeard in the mini page like in the screenshot
![Screenshot_20221229-091342_Chrome](https://user-images.githubusercontent.com/63660736/209913004-6c2e855b-e6cc-4cb4-ab27-37635f29011a.png)

**Comment by JingMatrix** [comment]
Couldn't reproduce this bug, could you see if it still exits in the lastest build?

**Comment by MohamadBayz** [comment]
Try enabling dev tools and then open this app [Cinexplorer](https://play.google.com/store/apps/details?id=com.fidloo.cinexplore) and choose a movie and click on the IMDB Icon
![Screenshot_20221229-154647_Cinexplore~2](https://user-images.githubusercontent.com/63660736/209953142-b1cf575b-5345-4946-abc5-bae9cc07fbca.png)
And then you will see that the open in chrome has disappeared 
![Screenshot_20221229-154742_Chrome](https://user-images.githubusercontent.com/63660736/209953218-3b8aa92f-b9d4-4ee0-ab12-dfc40b7a8c34.png)

**Comment by JingMatrix** [comment]
I cannot fix it, it depends on the developper of the app.
Maybe he/she made some change nobody knows.
You might try exit the dev options mode in Chrome and see if the menu appears or not.

**Comment by MohamadBayz** [comment]
It's weird even after disabling dev tools it's still showing dev tools

**Comment by MohamadBayz** [comment]
Should i re install chrome?

**Comment by JingMatrix** [comment]
Just reboot and disable my module will do the work.

**Comment by MohamadBayz** [comment]
Did it worked

**Comment by JingMatrix** [comment]
There is actually a bug with it, and it is fixed now by 5cb9da3a68ea42cb013bbdddf61859379b7e26fc.

**Comment by JingMatrix** [comment]
yeah, I forgot it.
