### ISSUE TITLE
WebView.getProviderClass errors after updating ChromeXt 

### ISSUE THREAD

**Issue by xiaowine** [JingMatrix/ChromeXt#140]
Edge Version:120.0.2210.64
This is the log file of the lsp, only the log of this module, which is of an abnormal size
[modules_2023-12-23T23_33_06.161152.log](https://github.com/JingMatrix/ChromeXt/files/13759504/modules_2023-12-23T23_33_06.161152.log)

**Comment by JingMatrix** [comment]
I tried Edge v120.0.2210.84 with both LSPatch and LSPosed, and they were working well.
Please ensure that you install the ChromeXt from [GitHub Actions](https://github.com/JingMatrix/ChromeXt/actions).

**Comment by xiaowine** [comment]
> I tried Edge v120.0.2210.84 with both LSPatch and LSPosed, and they were working well.我尝试了带有 LSPatch 和 LSPosed 的 Edge v120.0.2210.84，它们运行良好。 Please ensure that you install the ChromeXt from [GitHub Actions](https://github.com/JingMatrix/ChromeXt/actions).请确保从 GitHub Actions 安装 ChromeXt。



I did install ChromeXt from GitHub Action，but not work

[This is Edge apk](https://qqlittleice-my.sharepoint.com/:u:/g/personal/wine_qqlittleice_onmicrosoft_com/ET5cX6GEMT5Mv8bn3K-jzOEBELuSoMpdS0KoiHwBhVNcOw?e=dXPtMY)

**Comment by JingMatrix** [comment]
Still cannot reproduce your problem. I patched your provided APK, here is [the link](https://drive.google.com/file/d/1m1vBGNli5nHVfsI5fmhl85gCuAzu8zjg/view?usp=sharing).
Please install it to see if it works.
It might be that other Xposed modules on your devices is stopping ChromeXt from working.
You can try to disable them for a while.

**Comment by xiaowine** [comment]
> Still cannot reproduce your problem. I patched your provided APK, here is [the link](https://drive.google.com/file/d/1m1vBGNli5nHVfsI5fmhl85gCuAzu8zjg/view?usp=sharing).仍然无法重现您的问题。我修补了您提供的APK，这是链接。 Please install it to see if it works.请安装它，看看它是否有效。 It might be that other Xposed modules on your devices is stopping ChromeXt from working.可能是您设备上的其他 Xposed 模块阻止了 ChromeXt 的工作。 You can try to disable them for a while.您可以尝试禁用它们一段时间。

Maybe it's my system problem, he still reports the error

**Comment by JingMatrix** [comment]
1. What are your system's infomation? 
2. And are you using LSPosed or LSPatch?
3. Did other browsers, such as Chrome, work with ChromeXt on your devices?

**Comment by xiaowine** [comment]
> 1. What are your system's infomation?您的系统信息是什么？
> 2. And are you using LSPosed or LSPatch?您使用的是 LSPosed 还是 LSPatch？
> 3. Did other browsers, such as Chrome, work with ChromeXt on your devices?其他浏览器（例如 Chrome）是否在您的设备上支持 ChromeXt？

HpyerOS(Formerly known as MIUI) Android14
I use Lsposed

**Comment by xiaowine** [comment]
> 1. What are your system's infomation?您的系统信息是什么？
> 2. And are you using LSPosed or LSPatch?您使用的是 LSPosed 还是 LSPatch？
> 3. Did other browsers, such as Chrome, work with ChromeXt on your devices?其他浏览器（例如 Chrome）是否在您的设备上支持 ChromeXt？

其他浏览器我去测试一下

**Comment by xiaowine** [comment]
> 1. What are your system's infomation?
> 2. And are you using LSPosed or LSPatch?
> 3. Did other browsers, such as Chrome, work with ChromeXt on your devices?

I'll test other browsers

**Comment by xiaowine** [comment]
> 1. What are your system's infomation?
> 2. And are you using LSPosed or LSPatch?
> 3. Did other browsers, such as Chrome, work with ChromeXt on your devices?

chrome also reports an error, will it be related to the webview version, my version is 121.0.6164.18

**Comment by JingMatrix** [comment]
What are the other Magisk or LSPosed modules you are using? Could you please try to disable then for a while?

**Comment by xiaowine** [comment]
> What are the other Magisk or LSPosed modules you are using? Could you please try to disable then for a while?

Closed all other modules, still reported an error, lsposed version is 1.9.2 (7046)

**Comment by xiaowine** [comment]
> > What are the other Magisk or LSPosed modules you are using? Could you please try to disable then for a while?
> 
> Closed all other modules, still reported an error, lsposed version is 1.9.2 (7046)

I upgraded to 7050 with no change

**Comment by xiaowine** [comment]
> > > What are the other Magisk or LSPosed modules you are using? Could you please try to disable then for a while?
> > 
> > 
> > Closed all other modules, still reported an error, lsposed version is 1.9.2 (7046)
> 
> I upgraded to 7050 with no change

My friend's same system also reported an error

**Comment by JingMatrix** [comment]
It might be a bug of ChromeXt in my last commit.
I have pushed a new commit to fix it. Please try it in GitHub Actions.
If you still encounter errors, please provide a **new** log from LSPosed.

**Comment by xiaowine** [comment]
Now it's working
