### ISSUE TITLE
Support for MI Browser (Chinese version)

### ISSUE THREAD

**Issue by xiaowine** [JingMatrix/ChromeXt#141]
This is the log
[modules_2023-12-23T23_35_53.16947.log](https://github.com/JingMatrix/ChromeXt/files/13759512/modules_2023-12-23T23_35_53.16947.log)
This is apk
[apk](https://qqlittleice-my.sharepoint.com/:u:/g/personal/wine_qqlittleice_onmicrosoft_com/Eco4t4xBiwNLpDhKpDSg1vQBn0z2eR6XMHupO2sUSI5BqQ?e=uyfvq6)

**Comment by JingMatrix** [comment]
Thanks for the package, though I cannot install it on my device.
The provided log is almost empty, if possible please upload a valid one.

**Comment by xiaowine** [comment]
> Thanks for the package, though I cannot install it on my device.感谢您的软件包，尽管我无法将其安装在我的设备上。 The provided log is almost empty, if possible please upload a valid one.提供的日志几乎是空的，如果可能，请上传一个有效的日志。

[My mistakes](https://github.com/JingMatrix/ChromeXt/files/13759535/modules_2023-12-23T23_53_31.977884.log)

**Comment by JingMatrix** [comment]
I cannot help with this APK file, since `apktool` cannot decompile the apk without frameworks of Xiaomi OS.
If you want to help, please provide the framework files mentioned in this issue: https://github.com/iBotPeaches/Apktool/issues/2243

**Comment by xiaowine** [comment]
> I cannot help with this APK file, since `apktool` cannot decompile the apk without frameworks of Xiaomi OS.我无法帮助这个 APK 文件，因为 `apktool` 如果没有小米操作系统的框架，就无法反编译 apk。 If you want to help, please provide the framework files mentioned in this issue: [iBotPeaches/Apktool#2243](https://github.com/iBotPeaches/Apktool/issues/2243)如果您想提供帮助，请提供本期提到的框架文件：iBotPeaches/Apktool#2243

After the system update, currently I am aware of these files
[zip](https://qqlittleice-my.sharepoint.com/:u:/g/personal/wine_qqlittleice_onmicrosoft_com/EVAV9mYki6lDosEux7T4N3gBrXMEA2G4zrLh3TSImJ0PyQ?e=ZtZvtp)

**Comment by JingMatrix** [comment]
I still cannot decompile it, maybe you are missing these files:
1. ~~`framework-res.apk` from /system/framework~~
2. ~~`framework-ext-res.apk` from /system/framework/framework-ext-res~~
3. `miui.apk` from /system/app/miui
4. `miuisystem.apk` from /system/app/miuisystem
If you can find them, that is the best. If not, I have no other solutions yet.

**Comment by xiaowine** [comment]
> I still cannot decompile it, maybe you are missing these files:
> 
> 1. ~`framework-res.apk` from /system/framework~
> 2. ~`framework-ext-res.apk` from /system/framework/framework-ext-res~
> 3. `miui.apk` from /system/app/miui
> 4. `miuisystem.apk` from /system/app/miuisystem
>    If you can find them, that is the best. If not, I have no other solutions yet.

The current system does not have these files, maybe he changed the location

**Comment by JingMatrix** [comment]
I understand. It is a tricky problem since I don't have a Xiaomi device at my hand.
If you find them in other locations, please upload it here.

**Comment by xiaowine** [comment]
> I understand. It is a tricky problem since I don't have a Xiaomi device at my hand. If you find them in other locations, please upload it here.

Maybe you can use the Xiaomi system via gsi

**Comment by JingMatrix** [comment]
Sorry, but I have only one working Android device for both developping and daily life. Hence, I won't flash it.

**Comment by xiaowine** [comment]
> I understand. It is a tricky problem since I don't have a Xiaomi device at my hand. If you find them in other locations, please upload it here.

Then you can try dsu loading, which treats the system as a new loading system, and the original does not affect
Of course, if you'd like

**Comment by JingMatrix** [comment]
Sounds interesting, where can I find the official GSI of HyperOS?

**Comment by xiaowine** [comment]
> > I understand. It is a tricky problem since I don't have a Xiaomi device at my hand. If you find them in other locations, please upload it here.
> 
> Then you can try dsu loading, which treats the system as a new loading system, and the original does not affectOf course, if you'd like

Official did not provide, you can go to the xda forum to find the folk production

**Comment by JingMatrix** [comment]
I tested the browser apk downloaded from: https://browser-small-app.cn.uptodown.com/android 
And it works well now.
Maybe you can retry it on your device, or use the package in the given link.

**Comment by JingMatrix** [comment]
Hello, could you please show the result of 
```
adb shell ls /system/framework/
```

I need to figure out the location of framework on Xiaomi device to finally support the browser.

**Comment by xiaowine** [comment]
> Hello, could you please show the result of您好，您能否展示一下
> 
> ```
> adb shell ls /system/framework/
> ```
> 
> I need to figure out the location of framework on Xiaomi device to finally support the browser.我需要弄清楚框架在小米设备上的位置，才能最终支持浏览器。

```
MiuiBooster.jar
QPerformance.jar
QXPerformance.jar
UxPerformance.jar
WfdCommon.jar
abx.jar
am.jar
android.hidl.base-V1.0-java.jar
android.hidl.manager-V1.0-java.jar
android.test.base.jar
android.test.mock.jar
android.test.runner.jar
appwidget.jar
arm
arm64
bmgr.jar
boot-QPerformance.vdex
boot-UxPerformance.vdex
boot-WfdCommon.vdex
boot-apache-xml.vdex
boot-bouncycastle.vdex
boot-core-icu4j.vdex
boot-core-libart.vdex
boot-ext.vdex
boot-framework-adservices.vdex
boot-framework-graphics.vdex
boot-framework.vdex
boot-ims-common.vdex
boot-miui-enterprise-sdk.vdex
boot-miui-framework.vdex
boot-miui-telephony-common.vdex
boot-okhttp.vdex
boot-tcmiface.vdex
boot-telephony-common.vdex
boot-telephony-ext.vdex
boot-voip-common.vdex
boot.vdex
bu.jar
com.android.future.usb.accessory.jar
com.android.location.provider.jar
com.android.media.remotedisplay.jar
com.android.mediadrm.signer.jar
com.android.nfc_extras.jar
content.jar
ext.jar
framework-graphics.jar
framework-res.apk
framework.jar
hid.jar
ims-common.jar
incident-helper-cmd.jar
javax.obex.jar
locksettings.jar
monkey.jar
oat
org.apache.http.legacy.jar
org.apache.http.legacy.jar.prof
requestsync.jar
services.jar
services.jar.bprof
services.jar.prof
sm.jar
svc.jar
tcmclient.jar
tcmiface.jar
telecom.jar
telephony-common.jar
telephony-ext.jar
uiautomator.jar
uinput.jar
vendor.qti.hardware.data.connectionaidl-V1-java.jar
vendor.qti.hardware.radio.qtiradio-V1-java.jar
vendor.xiaomi.hardware.aidlbgservice-V1-java.jar
vendor.xiaomi.hardware.bgservice-V1.0-java.jar
vendor.xiaomi.hardware.misys-V1.0-java.jar
vendor.xiaomi.hardware.misys-V2.0-java.jar
vendor.xiaomi.hardware.misys-V4.0-java.jar
vendor.xiaomi.hardware.misys.V3_0.jar
voip-common.jar
vr.jar
wapicertstore.jar
```

**Comment by JingMatrix** [comment]
Thanks, please pack them and upload it here.
1. First you pull then locally: `adb pull /system/framework/`
2. Then, you pack the local `framework` folder into zip and upload it.

I hope those files are sufficient.

**Comment by xiaowine** [comment]
> Thanks, please pack them and upload it here.
> 
> 1. First you pull then locally: `adb pull /system/framework/`
> 2. Then, you pack the local `framework` folder into zip and upload it.
> 
> I hope those files are sufficient.

[link](https://qqlittleice-my.sharepoint.com/:u:/g/personal/wine_qqlittleice_onmicrosoft_com/ERvzzP6NnPdCqciu-52ibhMB5MPLRCCr0nTlX5KEJbeS3w?e=9sB27r)

**Comment by JingMatrix** [comment]
@xiaowine Could you please upload the Mi Browser apk again? Your previous link of it was expired.

**Comment by xiaowine** [comment]
> @xiaowine Could you please upload the Mi Browser apk again? Your previous link of it was expired.您能否再次上传 Mi Browser apk？您之前的链接已过期。

[link](https://qqlittleice-my.sharepoint.com/:u:/g/personal/wine_qqlittleice_onmicrosoft_com/ETAqUCuspN5IiavLmujfjScBJP1bIcuk0dkAw71sf8Ne8w?e=6Dnj7m)

**Comment by JingMatrix** [comment]
Please try the latest build.
In case that it doesn't work, please upload relevant logs.

```
adb logcat -s ChromeXt AndroidRuntime LSPatch LSPosed LSPatch-MetaLoader LSPatch-SigBypass LSPosed-Bridge LSPlant LSPosedContext zygisk64 LSPlt Dobby LSPosedService '*:F'
```
