### ISSUE TITLE
Cannot patch Brave v1.61.109 with ChromeXt 

### ISSUE THREAD

**Issue by TieuuLann** [JingMatrix/ChromeXt#142]
Why can I patch other browsers normally but Brave can't patch it? Just open it and exit the app

**Comment by JingMatrix** [comment]
Which APK you used to patch?
Please provide the APK that is not working with ChromeXt. Most likely, you picked up the wrong APK to patch;

**Comment by TieuuLann** [comment]
> Which APK you used to patch? Please provide the APK that is not working with ChromeXt. Most likely, you picked up the wrong APK to patch;

https://apkcombo.com/vi/brave-browser/com.brave.browser/ Before, it patched the browser's apk normally, but now it doesn't. I also tried it on the play store and it doesn't work either.

**Comment by JingMatrix** [comment]
Now this is fixed, please try it from the GitHub Actions.
If you still cannot patch it, please reopen this issue.
