### ISSUE TITLE
Google Chrome Crashes With The New Update [Bug]

### ISSUE THREAD

**Issue by MuhammadBayiz** [JingMatrix/ChromeXt#145]
Hi! Since i updated google chrome the module make chrome crash when its enabled. 

I'm on Google Chrome Version: 121.0.6167.101
And latest Chromext from action tab in GitHub
This is the [Google Chrome Crash Log
](https://bin.kv2.dev/~65b172ca5de7ed6bfdbc5fef)
And this is [Lsposed's Log](https://bin.kv2.dev/~65b174b75de7ed6bfdbc5ffb)

**Comment by JingMatrix** [comment]
Thanks for reporting, it is fixed now.
