### ISSUE TITLE
Support for Edge / Chrome 123

### ISSUE THREAD

**Issue by wuyongderen** [JingMatrix/ChromeXt#149]
Please fix，Google Browser Kernel 123 Out of service.

**Comment by JingMatrix** [comment]
Thanks for reporting the bug, it is fixed now. Please install the lastest version from [GitHub Actions](https://github.com/JingMatrix/ChromeXt/actions).

**Comment by wuyongderen** [comment]
Edge Canary 123.0.2383.0  It still doesn't work.

**Comment by wuyongderen** [comment]
> 感谢您报告错误，现已修复。 请从 [GitHub Actions ](https://github.com/JingMatrix/ChromeXt/actions) 安装最新版本。

Edge Canary 123.0.2383.0 It still doesn't work.

**Comment by JingMatrix** [comment]
It should be fixed now, thanks for reporting.
