### ISSUE TITLE
content cosmetic blocker & CSP Rules don't affect background tabs

### ISSUE THREAD

**Issue by MuhammadBayiz** [JingMatrix/ChromeXt#150]
Hi! I have set up multiple content cosmetic blocker using Eruda to block certain elements and csp to block certain urls but every time i open the tabs of that specific website in the background using "open in new tab in group" when i go to the tab the filters and csp rules don't apply to the tab unless i refresh it.

**Comment by MuhammadBayiz** [comment]
I think a similar issue was reported here sometime ago

**Comment by JingMatrix** [comment]
I just test it, on my phone, the filters are indeed applied.
That is to say, your issue cannot be reproduced.

**Comment by MuhammadBayiz** [comment]
Sorry for the late reply.
Can you test it in incognito mode? And try opening 10 tabs?

**Comment by JingMatrix** [comment]
Please provide the effective steps to reproduce the issue you described.
If not, at least upload a video describing your problem.
I still cannot reproduce your issue.

**Comment by MuhammadBayiz** [comment]
I just double checked again, and it seems the issue ever been foxed over the couple updates or it was some bug on my side.
Sorry for your trouble and thanks
