### ISSUE TITLE
Crashing in the latest version of edge.

### ISSUE THREAD

**Issue by Vader77Darth** [JingMatrix/ChromeXt#151]
I have no userscripts installed. This issue has started happening in 122.0.2365.56. Whenever, I try to access any website at all, the entire browser just crashes and closes. This happens across all my devices. 

https://github.com/JingMatrix/ChromeXt/assets/87441738/b84ccb35-7f7c-4623-99ff-3ecf4488f612

**Comment by JingMatrix** [comment]
Cannot reproduce your problem, maybe you didn't try the latest version of ChromeXt.

**Comment by Vader77Darth** [comment]
Ah. I was using the version in the LSPosed repository which I now know is out of date. Do you have plans to keep the releases page up to date as it would make updating the app much easier?

**Comment by JingMatrix** [comment]
You are right, I should try to keep the release page up to date. (Being a bit lazy)
