### ISSUE TITLE
Support Qihoo browser

### ISSUE THREAD

**Issue by 183868hlj** [JingMatrix/ChromeXt#154]
请兼容360极速浏览器v3.3.0.300内测版，没加固的。
Please be compatible with 360 Speed Browser v3.3.0.300 beta version, unreinforced

**Comment by JingMatrix** [comment]
If you can, please update an APK file or a valid and secure source to download it.

**Comment by 183868hlj** [comment]
> If you can, please upload an APK file or a valid and secure source to download it.

Please check as soon as possible：
https://www.123pan.com/s/kur5Vv-BJorv.html  提取码：N8r6

**Comment by JingMatrix** [comment]
The browser doesn't support remote debugging, which causes lots of difficulties for ChromeXt to support it.
For unkown reason, current support isn't perfect.
You can pick up the lastest build from GitHub Actions and try it at your own risks.

**Comment by 183868hlj** [comment]
> The browser doesn't support remote debugging, which causes lots of difficulties for ChromeXt to support it.
> For unkown reason, current support isn't perfect.
> You can pick up the lastest build from GitHub Actions and try it at your own risks.

Okay, thank you!
