### ISSUE TITLE
Regarding the issue of full screen gesture return for lspatch (non white screen and non flashing version)关于lspatch（不白屏不闪退版）的全面屏手势返回问题

### ISSUE THREAD

**Issue by 183868hlj** [JingMatrix/ChromeXt#155]
I used the lspatch you modified (no white screen, no flashing version) and loaded it into the Mulch browser, causing difficulty in returning full screen gestures with shadows. Please fix it!
我用您修改了的lspatch（不白屏不闪退版），装入mulch浏览器，造成全面屏手势返回困难，有阴影，请修复！
![Screenshot_2024-03-17-04-23-34-24_438047d178ae0bdcccdfb4df8486f35b](https://github.com/JingMatrix/ChromeXt/assets/149270855/4ecaf16d-3109-41f1-9df6-c45c561cdd47)

**Comment by JingMatrix** [comment]
That is the intended behavior, you can disable the option `Browser gesture navigation` in the `Developer options`.
See [instructions in the video](https://youtu.be/1Qm4dU-XnJM?si=mSf9JyAvwspmucgo&t=940).

**Comment by 183868hlj** [comment]
> That is the intended behavior, you can disable the option `Browser gesture navigation` in the `Developer options`。这是预期的行为，您可以禁用 `Developer options` 中的选项 `Browser gesture navigation` 。 See [instructions in the video](https://youtu.be/1Qm4dU-XnJM?si=mSf9JyAvwspmucgo&t=940)。 请参阅视频中的说明。

感谢大佬！
