### ISSUE TITLE
Simplified view in Kiwi Browser

### ISSUE THREAD

**Issue by BiponD97** [JingMatrix/ChromeXt#157]
There is simplified view button missing in Kiwi Browser unlike chrome. Reporting to the latest 3.8.1 release.

**Comment by JingMatrix** [comment]
It is fixed already, you can find the latest build from [GitHub Actions](https://github.com/JingMatrix/ChromeXt/actions).

See [my channel](https://youtu.be/1Qm4dU-XnJM?feature=shared&t=554) for video instructions.
