### ISSUE TITLE
Bengali Font bug in Simplified View of Kiwi Browser

### ISSUE THREAD

**Issue by BiponD97** [JingMatrix/ChromeXt#158]
![Screenshot_20240322-213853_Kiwi Browser](https://github.com/JingMatrix/ChromeXt/assets/100799060/fa3669d0-79c5-4a81-9858-2a1d7841fbd3)

Sometimes Kiwi Browser Simplified View do not showing article Content of Bengali font. Also similar problem I faced in the chrome browser

**Comment by JingMatrix** [comment]
What is the hyperlink of your examplar page? Are you sure it is really related to `Bengali Font`?
Maybe it simply ignores any similar contents of similar page layouts.
Most likely, I cannot help with this features/bugs of Chrome distiller (reader mode) function.
It is the job of Chromium development team.
