### ISSUE TITLE
Feature request: Add support for telegram bot web apps

### ISSUE THREAD

**Issue by Talisman9964** [JingMatrix/ChromeXt#171]
Would be awesome if i was able to inspect my telegram bot web apps on mobile directly in telegram . If possible please add support for telegram web apps webview to chromext . I am not sure if telegram android uses the system webview or not but it seems like it does

**Comment by JingMatrix** [comment]
If you cannot do it with Chrome on desktops, then you cannot do it with ChromeXt.
Telegram bots codes are mostly server side, not executed inside your client browsers.

**Comment by Talisman9964** [comment]
> If you cannot do it with Chrome on desktops, then you cannot do it with ChromeXt. Telegram bots codes are mostly server side, not executed inside your client browsers.

Indeed , usually telegram bots are server side applications but nowadays bots can launch a webview with a web ui for better user experience , and yes we can debug them using chrome devtools on desktop . You can find more info on https://core.telegram.org/bots/webapps#debug-mode-for-mini-apps . 

telegram also has a demo web app called [@durgerking](https://t.me/durgerkingbot)

**Comment by JingMatrix** [comment]
Thank you for the information.
You may provide more if you proceed to investigate this issue, which would be great.
In ChromeXt, there is more or less or re-implement of WebSocket messaging.
See https://github.com/JingMatrix/ChromeXt/tree/master/app/src/main/java/org/matrix/chromext/devtools

Moreover, the front-end of ChromeXt deliberately ignore debug sessions for service-workers, which might cause the issue.

**Comment by Tanzin01** [comment]
@Talisman9964  were you able to find a solution?
