### ISSUE TITLE
Install UserScripts from gist.github.com

### ISSUE THREAD

**Issue by jinshuqishi2019** [JingMatrix/ChromeXt#172]
greasyfork.org里面的脚本点击安装可以识别安装，但是一样的脚本（内容和名称一样）迁移到gist.github.com就不能识别安装。

**Comment by JingMatrix** [comment]
Please provide the concrete URLs of what you want to show.
Usually, you need use a raw link to the script to install it.

**Comment by jinshuqishi2019** [comment]
好的，例如我在greasyfork随便找到其中一个脚本。
不显示安装:
https://gist.github.com/jinshuqishi2019/55b3bce2dba1677d18b3f053c9c0af26/raw/Greasy%2520Fork%2520%25E5%25A2%259E%25E5%25BC%25BA.user.js
显示安装界面：
https://update.greasyfork.org/scripts/467078/Greasy%20Fork%20Enhance.user.js

**Comment by JingMatrix** [comment]
Thanks for reporting this bug, it is fixed now.
