### ISSUE TITLE
Global settings for Eruda console 

### ISSUE THREAD

**Issue by Joristdh** [JingMatrix/ChromeXt#174]
Would it be possible to have global preferences for the Eruda console? Currently, settings are stored locally in localStorage, which means they don't persist between sites.

The ability to globally set the theme and size for all Eruda windows like this would be greatly appreciated!

**Comment by JingMatrix** [comment]
This is surely possible, but I don't think that ChromeXt should bother to do this.

However, you can write a userscipt to achieve that.

**Comment by Joristdh** [comment]
Wow, you are absolute right! Honestly, can't believe I didn't think of this myself.. 

Anyways, thanks for the quick reply and I'll leave link to my [userscript ](https://greasyfork.org/en/scripts/497352-eruda-defaults) to possibly help other users. 

Keep up the great work!
