### ISSUE TITLE
The script failed to execute.

### ISSUE THREAD

**Issue by duchao** [JingMatrix/ChromeXt#179]
Hello, when I was using the script below, it did not execute correctly. After debugging, I found that require does not support // @require data:application/javascript,window.Vue%3DVue%3B data format.  

https://greasyfork.org/zh-CN/scripts/436994-%E8%B6%85%E6%98%9F%E5%AD%A6%E4%B9%A0%E9%80%9A%E6%BB%A1%E5%88%86%E5%8A%A9%E6%89%8B-%E6%94%AF%E6%8C%81%E4%BB%BB%E5%8A%A1%E7%82%B9%E8%87%AA%E5%8A%A8%E8%B7%B3%E8%BD%AC-%E7%AB%A0%E8%8A%82%E6%B5%8B%E9%AA%8C-%E4%BD%9C%E4%B8%9A-%E8%80%83%E8%AF%95%E5%85%A8%E7%BD%91%E6%A3%80%E7%B4%A2%E7%AD%94%E6%A1%88-%E7%AE%80%E7%AD%94%E9%A2%98%E6%94%AF%E6%8C%81chatgpt%E5%AF%B9%E6%8E%A5-%E9%9F%B3%E9%A2%91-%E8%A7%86%E9%A2%91%E5%85%A8%E8%87%AA%E5%8A%A8%E9%9D%99%E9%9F%B3%E6%92%AD%E6%94%BE-%E5%8F%AF%E8%A7%86%E5%8C%96%E5%8F%82%E6%95%B0%E9%85%8D%E7%BD%AE

**Comment by JingMatrix** [comment]
The CDN URLs are not working in France, I manually changed them in my local test environment. And here is a screenshot when it works:
![Screenshot_20240725-171211](https://github.com/user-attachments/assets/10392d26-3bf8-4ae9-ad9c-d9b8abcb0a83)

I wish you good luck with this script.
