### ISSUE TITLE
License question

### ISSUE THREAD

**Issue by IzzySoft** [JingMatrix/ChromeXt#18]
I just wonder what exact license is your module using? The code refers to a LICENSE file I could not find, and vaguely speaks of "a BSD-style license". Maybe you could add that LICENSE file to clarify? Thanks in advance!

**Comment by JingMatrix** [comment]
That was the license belongs to the Chromium project.

Currently, this project hasn't declared any license. This means that all rights are resevered for now.

Surely, I will release an open source license soon.

**Comment by IzzySoft** [comment]
Thanks for the swift response – and glad to read F/LOSS is planned! I'll then stay subscribed here and patiently wait for its arrival.

**Comment by IzzySoft** [comment]
No pressure, just out of curiosity: Is there an ETA for soon™? :see_no_evil:

**Comment by JingMatrix** [comment]
This project depends on reverse engineering Android Chrome, that causes a bit concern.
I am not sure it is legal to add a licence.
Also, I am expecting more stars to give a license.
Only enough interests from others make an open source project meaningful to me, but currently this project is little known.

I should add a license in the 3.0 version. This idea is delaying my release of ChromeXt 3.0.
By the way, any license would you suggest given the RE concern above?

**Comment by IzzySoft** [comment]
OK, understood the concerns. And if I should guess one: what license do Chromium or Bromite use? Guess that would be the closest match if yours comes from Chrome, too. But IANAL, so I cannot really tell. Will you drop a note here when decided and applied? Thanks!

**Comment by JingMatrix** [comment]
It is true that I use Chromium code as refrences, so does Bromite.
But Bromite doesn't use its decompiled smali codes, while I do.
As you might have observed, after each major Android Chrome updates, I made commits to change the correponding smali names.
And those names require RE, not only the source code of Chromium.
Note also that the RE is made upon Chrome, not Chromium.
Chrome is a Google's commercial product, unlike Chromium.
If some derivative of this project impair Google's profit, I might be the first one to blame.

I will tell here when I firgure it out. There might be few examples I can refer to.

One way to avoid this, is to have another sever that provides smali names for Chrome updates. This way separates RE parts.

**Comment by JingMatrix** [comment]
The code is now free of RE, and the license is GPL-3.0 license.

**Comment by JingMatrix** [comment]
@IzzySoft Could you please update the description of `ChromeXt` on your F-Droid repo?
Here are the main changes:
1. The application icon has changed
2. The supported browsers are not restricted to `Android Chrome`
3. There is no more restriction when installing UserScripts from `raw.githubusercontent.com`, so please remove it from the description.
4. If possible, please add the YouTube link, which is more informative.*

Thanks in advance.

**Comment by IzzySoft** [comment]
@JingMatrix wil do. But may I recommend a better solution for the future? None of the 4 items would require my interaction if you'd establish Fastlane structures in your repo here (you can use my [Fastlane Cheat Sheet](https://gitlab.com/-/snippets/1895688) for guidance – and I could offer to send you a PR with an initial setup of what's established here). That way you would be in control of all that yourself. How does that sound?

Further, maybe you could [pick a badge](https://gitlab.com/IzzyOnDroid/repo/#if-my-app-is-available-here-do-you-have-a-badge-i-can-use-to-link-to-it) to add to your Readme, pointing to [your app in my repo](https://apt.izzysoft.de/packages/org.matrix.chromext/)?

For 1 I'd need the icon. I cannot find any in your repo. Once you provide me one, I'll do the update (including the other parts). Thanks!

**Comment by IzzySoft** [comment]
1. could not find the icon (as outlined above), failed to convert the current vector graphic (`ic_launcher.xml`) – but managed to convert the `ic_chrome.xml` with some manual work
2. updated short description to "UserScripts and Dev Tools support for Chromium based and WebView based browsers"
3. removed the "error handling" part concerning `raw.githubusercontent.com`, rephrasing it as alternative possibility for script installation
4. YT link added as `video.txt` (Fastlane)

Changes should be in effect with the next sync around 6 pm UTC. I still recommend establishing Fastlane in your repo (above offer stands) and look forward to the badge being added :wink:
