### ISSUE TITLE
Eruda isn't working [Bug Report]

### ISSUE THREAD

**Issue by MuhammadBayiz** [JingMatrix/ChromeXt#182]
I keep getting this error on Eruda console 
[Eruda] Something wrong when initializing tool resources: c is not a function
[Eruda] Something wrong when initializing tool info: c is not a function

I've tried clearing ChromeXt data uninstalling and reinstalling multiple times and finally I've cleared my chrome data and uninstalled & reinstalled it but all this didn't fix it.

I couldn't find logs for this bug in LSposed, where i could log eruda if it's needed?

**Comment by JingMatrix** [comment]
It was already fixed by 47e5133 few days ago, please update your ChromeXt from GitHub Actions.

**Comment by MuhammadBayiz** [comment]
Thanks very much
