### ISSUE TITLE
Regression: Eruda Info Panel 'c is not a function' Error Reappears

### ISSUE THREAD

**Issue by huajiqaq** [JingMatrix/ChromeXt#185]
The Eruda information panel in the chromext module is again encountering the "c is not a function" error in the latest version, which was previously fixed. However, in the latest version of eruda.js, it seems that the previous fix was reverted, and when I changed the c function in the latest version to the definition of the c function in eruda.js from 3.2.0, the problem was solved.

**Comment by JingMatrix** [comment]
That's fairly strange, and impossible actually.
I cannot reproduce it with latest build of ChromeXt and Eruda 3.2.2.
You may try to fully restart your Browser app to see if the problem persist, and update your Eruda.

**Comment by huajiqaq** [comment]
I downloaded it through the lsposed built-in module and the one in the build has fixed the problem.
