### ISSUE TITLE
Brave 1.68.133 shows no signs of being patched despite successful patching

### ISSUE THREAD

**Issue by CodingArdor** [JingMatrix/ChromeXt#186]
Brave 1.68.133 shows no signs of being patched despite successful patching via either LSPatch on Windows or on Android:
- `ChromeXt is not installed` shown in frontend (https://jingmatrix.github.io/ChromeXt/)
- `.user.js` page (e.g., https://update.greasyfork.org/scripts/483164/Quantumjs.user.js) does not trigger installation prompt
- Eruda console menu item is not present

Details are as follows:
- **Android version:** Android 14 arm64-v8a
- **Rooted?** No
- **Browser to patch:** Brave v1.68.133 
- **APK source:** https://www.apkmirror.com/apk/brave-software/brave-browser/brave-browser-1-68-133-release/brave-private-web-browser-vpn-1-68-133-android-apk-download/

**Patch attempt 1 (LSPatch on Windows)**
- **Patch method:** `java -jar jar-v0.6-419-release.jar brave.apk -d -v -m ChromeXt-signed.apk --force`
-  `jar-v0.6-419-release.jar` from https://github.com/JingMatrix/LSPatch/actions/runs/10236530167
- `ChromeXt.apk` from https://github.com/JingMatrix/ChromeXt/actions/runs/10280284319
- Existing Brave was uninstalled prior to `apk install brave-419-lspatched.apk`

**Patch attempt 2 (LSPatch on Android)**
- **Patch method:** Via LSPatch (`manager-v0.6-419-release.apk`) on Android; patched APK installed manually via file manager
- `manager-v0.6-419-release.apk` from https://github.com/JingMatrix/LSPatch/actions/runs/10236530167
- Existing Brave was uninstalled prior to installation of patched APK

Please let me know if more information is needed.

**Comment by JingMatrix** [comment]
Could you please try this build of ChromeXt: https://github.com/JingMatrix/ChromeXt/actions/runs/10434320142
