### ISSUE TITLE
ChromeXt v3.8.1Not compatible with Samsung browser27.0.0.26

### ISSUE THREAD

**Issue by 183868hlj** [JingMatrix/ChromeXt#187]
ChromeXt v3.8.1Not compatible with Samsung browser27.0.0.26，Will cause to open on the flash back, UsefulLSPatch0.6（405）
ExchangeLSPatch：0.6（7024）Version, it can be opened, but it cannot be loaded, and there will be no response

**Comment by JingMatrix** [comment]
Please ensure that you are using the ChromeXt and LSPatch from GitHub Actions

**Comment by 183868hlj** [comment]
> Please ensure that you are using the ChromeXt and LSPatch from GitHub Actions：https://github.com/JingMatrix/LSPatch

**Comment by JingMatrix** [comment]
Please donwload LSPatch from **GitHub Actions**: https://github.com/JingMatrix/LSPatch/actions/runs/10236530167

**Comment by 183868hlj** [comment]
> Please donwload LSPatch from **GitHub Actions**: https://github.com/JingMatrix/LSPatch/actions/runs/10236530167

非常感谢！
