### ISSUE TITLE
ChromeXt doesn't work on latest Brave Browser release (1.68.141)

### ISSUE THREAD

**Issue by Lumaeris** [JingMatrix/ChromeXt#188]
As suggested in the instructions I'm using the latest builds of LSPatch fork and ChromeXt from GitHub Actions. After embedding the module the browser installed normally, but ChromeXt is not detected as shown in the screenshot.

![Screenshot_20240815-205941.jpg](https://github.com/user-attachments/assets/f99f9a30-2d8b-4b97-84d6-70a20921d47b)

I'm using the APK from the official repository. My device is not rooted, Android 12

**Comment by JingMatrix** [comment]
Cannot reproduce the issue in my devices for Brave 1.70.80 and 1.68.137, which are available from my Google Play store.
Please ensure you are following the correct processure of patching the app, see the video in README.
