### ISSUE TITLE
Setting "default-src 'self'…" locks you from using Eruda

### ISSUE THREAD

**Issue by MuhammadBayiz** [JingMatrix/ChromeXt#189]
Hi, i have set the csp rule "default-src 'self'…" on a website now I can't open eruda no longer and the csp rule broke most of the websites functionality now is there a way to manually change the csp rule? I have root i did search in `/data/data/com.android.chrome` and `/storage/emulated/0/Android/data/com.android.chrome` but couldn't find anything related to changing the csp rule. Is there any way i could fix this beside uninstalling and reinstalling ChromeXT?

**Comment by JingMatrix** [comment]
The rules are stored in `/data/data/com.android.chrome/shared_prefs/CSPRule.xml`, you can directly edit or delete it if you want.
As an advice, you may want to use the `script-src 'self'` rule.

**Comment by MuhammadBayiz** [comment]
Found it.
Yes this time I'll tinker with script-src, thanks
