### ISSUE TITLE
可以写一个教程吗 我无法使用

### ISSUE THREAD

**Issue by wu-ya** [JingMatrix/ChromeXt#19]
我没办法用 chrome是play下载的最新版 chromext也是最新版
但是没办法用 解包了chrome 发现没有基础没有教程没办法弄
![Screenshot_2023-01-05-00-32-48-600_com miui home](https://user-images.githubusercontent.com/84127601/210931225-7681aca4-ad5e-4cdd-b0bf-ea8b461d7d01.jpg)

**Comment by JingMatrix** [comment]
1. 确保你是从 GitHub Action 上下载的最新版本。Release 上的版本可能还不支持你安装的 Chrome 。
2. 仔细阅读 Reademe，可以借助翻译工具来理解。
3. 提供 Lsposed 的相关 Log 来帮助作者诊断问题。

**Comment by JingMatrix** [comment]
现在有了视频教程，你可以在 B 站找到它：https://www.bilibili.com/video/BV1TV4y1b7zR/
