### ISSUE TITLE
Eruda Console Shortcut Not Showing In Lastest Brave Browser

### ISSUE THREAD

**Issue by Aerty-G** [JingMatrix/ChromeXt#191]
In Previous version of Brave Browser The shortcut in three dot show up, but in the lastest version of Brave Browser Console in three dot disappear. 

Brave Browser: v1.69.160
ChromeXt: v3.8.2
Android 12 MIUI 13
![Screenshot_2024-09-10-16-11-33-298_com brave browser](https://github.com/user-attachments/assets/4a6d76a5-a0cd-4a36-9d8a-047085fecc0f)

**Comment by JingMatrix** [comment]
Did you use the ChromeXt from the GitHub Actions? I supposed that this should have been fixed three weeks ago.

**Comment by Aerty-G** [comment]
ah, thanks now it's fixed.

**Comment by Aerty-G** [comment]
Sup Sir, The Console Now Showing In Brave Again.
Barve Version: 1.70.123

**Comment by Aerty-G** [comment]
Android 13
MIUI 14.0.7

**Comment by JingMatrix** [comment]
I am using Brave v1.71.118 and the console menu is shown.

**Comment by Aerty-G** [comment]
> I am using Brave v1.71.118 and the console menu is shown.

![Screenshot_2024-11-04-15-31-42-198_com brave browser](https://github.com/user-attachments/assets/df36d329-85a6-4c48-9c05-9949d6bdb8ec)
Bug On Me Huh...

**Comment by JingMatrix** [comment]
Maybe try restarting your phone, and ensure you are using latest CI build.

**Comment by Aerty-G** [comment]
> Maybe try restarting your phone, and ensure you are using latest CI build.

https://github.com/JingMatrix/ChromeXt/actions/runs/11087956856 ?
Yes I Do, i use the lastest CI build. But Still not showing. 
I tried opening chrome instead, it's working properly. 
idk why
btw restarting my phone not changing anything, i already tried it

**Comment by JingMatrix** [comment]
Please update your logs generated by LSPosed, so that I can analyze deeper.

**Comment by Aerty-G** [comment]
> Please update your logs generated by LSPosed, so that I can analyze deeper.

Um, Logcat? Verbose LSP? Module Log LSP?
which one?

**Comment by JingMatrix** [comment]
Please upload the zip archive file generated by LSPosed.

**Comment by Aerty-G** [comment]
[LSPosed_2024-11-05T19_47_23.043304.zip](https://github.com/user-attachments/files/17645861/LSPosed_2024-11-05T19_47_23.043304.zip)
Here

**Comment by JingMatrix** [comment]
It is the problem of your LSPosed.
LSPosed_mod is not working on your system. Please use [JingMatrix/LSPosed](https://github.com/JingMatrix/LSPosed).

**Comment by Aerty-G** [comment]
Aight
