### ISSUE TITLE
Console not shown in Chrome 110

### ISSUE THREAD

**Issue by c1400700226** [JingMatrix/ChromeXt#192]
![Screenshot_2024-09-22-20-41-48-431_com android chrome](https://github.com/user-attachments/assets/84dc0529-fbf8-4ba0-b78b-385215d1c145)
![Screenshot_2024-09-22-20-41-52-990_com android chrome](https://github.com/user-attachments/assets/b1fd559a-810b-44c3-bb81-0a82fa0f7aa0)
![Screenshot_2024-09-22-20-41-55-133_com android chrome](https://github.com/user-attachments/assets/16112a2d-7ce3-4518-9021-2d974ef6cf42)
I just updated chromext from 3.7.0 to 3.8.2, after updating the console disappeared from menu. Downgrading to 3.7.0 isn't possible, as eruda was updated.

**Comment by JingMatrix** [comment]
Please update your Chrome browser. ChromeXt focus on supporting newer versions of Chrome.
