### ISSUE TITLE
Support Adding Cosmetic/Filter Lists from URL for all sites Globally

### ISSUE THREAD

**Issue by MulverineX** [JingMatrix/ChromeXt#197]
`https://raw.github.com/reek/anti-adblock-killer/master/anti-adblock-killer-filters.txt`

`https://gitflic.ru/project/magnolia1234/bypass-paywalls-clean-filters/blob/raw?file=bpc-paywall-filter.txt`

I'd like to enable these filter lists for all sites and have them auto update.

**Comment by JingMatrix** [comment]
This is not possible in near future, hence it is better for you to add special list for certain most visited websites of your daily life.

**Comment by MulverineX** [comment]
the biggest benefits of these are on random news sites off Google Discover & Reddit, not really feasible to manually do it. Bummer

**Comment by JingMatrix** [comment]
If you have AdAway, then only few rules need to be added manually.

**Comment by MulverineX** [comment]
I do have AdAway, these are all cosmetic and paywall fixers, which don't function on `hosts` blocks alone and need a runtime to work

**Comment by JingMatrix** [comment]
See #124 for my complete arguments regarding AdBlocking.
