### ISSUE TITLE
求助

### ISSUE THREAD

**Issue by svohoyzvozyvs** [JingMatrix/ChromeXt#20]
接下来该如何使用呢
![Screenshot_2023-01-07-00-45-23-160_com android chrome](https://user-images.githubusercontent.com/94443781/211058061-6f275900-9d2c-4d78-898e-e1d43ece55cc.jpg)

**Comment by JingMatrix** [comment]
去各大脚本网站，安装你想要的脚本即可。

**Comment by svohoyzvozyvs** [comment]
![Screenshot_2023-01-07-23-18-52-252_com android chrome](https://user-images.githubusercontent.com/94443781/211157957-c9df7384-f5b8-4705-aca2-cf75ab244182.jpg)
只有第二个生效，第一个不生效是什么原因呢

**Comment by JingMatrix** [comment]
如果具备相关知识的话，请提供有效的脚本出错相关信息，一般可以在开发者工具中找到。

如果没有这样的知识，一般的建议是不要使用这种大型脚本。使用小脚本实现小功能，这样出错率更低。


Le sam. 7 janv. 2023, 16:21, svohoyzvozyvs ***@***.***> a
écrit :
