### ISSUE TITLE
Please support herondBrowser

### ISSUE THREAD

**Issue by wuyongderen** [JingMatrix/ChromeXt#203]
Please support this browser，thanks
https://play.google.com/store/apps/details?id=com.herond.android.browser

**Comment by wuyongderen** [comment]
After the patch, the browser cannot open any web page

**Comment by JingMatrix** [comment]
How do you patch it? You need to use JingMatrix/LSPatch.

**Comment by wuyongderen** [comment]
I used the one here to fix it.
https://github.com/JingMatrix/LSPatch/actions/runs/11950030094

**Comment by JingMatrix** [comment]
You need check the `Inject dex loader` when you patch a browser.

**Comment by wuyongderen** [comment]
I patched it with this version and it works.
https://github.com/JingMatrix/LSPatch/actions/runs/11618882230
