### ISSUE TITLE
Vivaldi options

### ISSUE THREAD

**Issue by Achyuth072** [JingMatrix/ChromeXt#209]
I patched vivaldi with LSpatch and got chromext working but how do I access the eruda console? 

![Screenshot_2024-12-14-10-31-00-77_ceec59aa567a648df9ce2533f307b5ac.jpg](https://github.com/user-attachments/assets/3e575a87-db77-41ba-827a-69eeff09d587)

**Comment by JingMatrix** [comment]
Please watch the YouTube tutorial video in README. It is in the page menu.

**Comment by Achyuth072** [comment]
> Please watch the YouTube tutorial video in README. It is in the page menu.

Hello I watched the video but I saw that in the browser you used it showed up in the context menu and for edge it showed up else where. For Vivaldi I couldn't find any such option.
![Screenshot_2024-12-14-11-49-19-51_ceec59aa567a648df9ce2533f307b5ac.jpg](https://github.com/user-attachments/assets/ecd4bc49-28a2-45ff-871e-e758fb5df9b9)

![Screenshot_2024-12-14-11-49-30-79_ceec59aa567a648df9ce2533f307b5ac.jpg](https://github.com/user-attachments/assets/426f2a7d-ca68-47d4-bf68-2003e12134af)

**Comment by JingMatrix** [comment]
You need to update ChromeXt. Please use the version from GitHub Actions

**Comment by Achyuth072** [comment]
> You need to update ChromeXt. Please use the version from GitHub Actions 

I'm using the one from [here](https://github.com/JingMatrix/ChromeXt/actions/runs/12219319583). It seems to latest version unless I'm wrong.

**Comment by JingMatrix** [comment]
I see, it then could be that I should update the support of ChromeXt for their recent updates.
Will work on this next week.

**Comment by JingMatrix** [comment]
It works on version 7.0.3505.121 of com.vivaldi.browser. what is your version of Vivaldi?

**Comment by Achyuth072** [comment]
> It works on version 7.0.3505.121 of com.vivaldi.browser, what is your version of Vivaldi?

I was trying that on snapshot v7.1.3547.3 so that I wouldn't lose data, did it on regular vivaldi and it works, thanks! 
Sorry if I wasted your time using Snapshot!

**Comment by JingMatrix** [comment]
@Achyuth072 No worries, hoping ChromeXt will still work when the snapshot gets stable.
