### ISSUE TITLE
I can't use "ChromeXt is not installed"

### ISSUE THREAD

**Issue by chuwza** [JingMatrix/ChromeXt#22]
Hello, developer, it shows: ChromeXt is not installed. Android 11, already tested Chrone 109 apk/xapk

this is log

[LSPosed_2023-02-16T20_13_37.035.zip](https://github.com/JingMatrix/ChromeXt/files/10755887/LSPosed_2023-02-16T20_13_37.035.zip)

![Screenshot_20230216-201939_Chrome](https://user-images.githubusercontent.com/30049891/219362993-6f42b719-d026-4d14-8355-d53f2b515526.png)

**Comment by JingMatrix** [comment]
Hi!
Did you try with the latest build from the Github Action? The version from the release page may not work for you.
I checked your log, it didn't capture logs from ChomeXt.
Could you please clear your Xposed log, and then __retstart__ Chrome fully so that something could be captured?
After this, please upload your log here.
If you can, there are only few logs are relevant, maybe you can copy paste them directly.

**Comment by JingMatrix** [comment]
I found the relevant log now,  it showed that you should install currently the latest version from [Github Action](https://github.com/JingMatrix/ChromeXt/actions/runs/4143207032).

**Comment by chuwza** [comment]
> Hi! Did you try with the latest build from the Github Action? The version from the release page may not work for you. I checked your log, it didn't capture logs from ChomeXt. Could you please clear your Xposed log, and then **retstart** Chrome fully so that something could be captured? After this, please upload your log here. If you can, there are only few logs are relevant, maybe you can copy paste them directly.

Thanks for your reply, I am using the latest version 2.0. Here's the log, as it couldn't be reproduced in Lsposed, I used a screenshot and a zip file
![screenshot_1676551089351](https://user-images.githubusercontent.com/30049891/219367460-aa5c9ed4-9eb5-4e7e-b251-e5d9d4d30fdc.png)
[LSPosed_2023-02-16T20_38_14.499.zip](https://github.com/JingMatrix/ChromeXt/files/10756053/LSPosed_2023-02-16T20_38_14.499.zip)

**Comment by JingMatrix** [comment]
It is consfusing, but ChromeXt 2.0 is not the latest one. Please follow my previous comment to install from Github Action (it is explained partly in the README).

**Comment by chuwza** [comment]
> It is consfusing, but ChromeXt 2.0 is not the latest one. Please follow my previous comment to install from Github Action (it is explained partly in the README).

thank you I used the latest version it works

**Comment by JingMatrix** [comment]
I just updated the code to support Chrome v110, if you want, please try it and see if it works as well.
I cannot test it by myself because the apk I downloaded is alway older the one I installed from Google Play. To downgrade, I need to clear data, that is inconvient for me.

**Comment by chuwza** [comment]
> I just updated the code to support Chrome v110, if you want, please try it and see if it works as well. I cannot test it by myself because the apk I downloaded is alway older the one I installed from Google Play. To downgrade, I need to clear data, that is inconvient for me.

it doesn't work

**Comment by JingMatrix** [comment]
Can you please post the relevant log here?

**Comment by chuwza** [comment]
> Can you please post the relevant log here?

-part 4 start-

| 2023-02-17T11:41:38.047 10172: 20188: 20188 I/LSPosed-Bridge Loading

module cc.aoeiuv020. iamnotdisabled.hook from /data/app/-4yevAITBITT5VKJNg2YTZg--/ cc.aoeiuv020.iamnotdisabled.hook. MainHook | 2023-02-17T11:41:38.053 10172; 20188: 20188 I/LSPosed- Bridge I initzygote: /data/app/-4yevAITBITTSVKJwg2YTZg-/ org.matrix.chromext-xbqEgJpfHiilZFrUfDJSNA--/base.apk 12023-02-17T11:41:38, 133 10172: 20188: 20188 I/L5Posed-Bridge | module cc.aoeiuv020. iamnotdisabled.hook from /data/app/-4yevAITBITT5VKJNg2YTZg--/ | 2023-02-17T11:41:39,215 10172: 20290: 20290 I/LSPosed- Bridge I initzygote: /data/app/-4yevAITBITTSVKJwg2YTZg-/ cc.aoeiuv020.ianotdisabled.hook-J5DQhzWU-109YrnfgEJUGA--/base.apk 1 2023-02-17T11:41:39.226 10172: 20290: 20290 L/L5Posed-Bridge | Loading module org.matrix.chromext from /data/app/~dF6dDZCj51qD1BXMVGxdfw--/ org.matrix.chromext-xbqEgJpfHiilZFrUfDJSNA--/base.apk 1 2023-02-17T11:41:39.293 10172: 20290: 20290 I/L5Posed-Bridge 1 | 2023-02-17T11:41:41.093 10172; 20188: 20188 I/LSPosed-Bridge 1 java.lang.IllegalArgumentException: Wrong number of arguments: expected 0, got 1 I 2023-02-17T11:43:45.623 10172: 20188: 20188 I/L5Posed-Bridge 1 java.lang.IllegalArgumentException: wrong number of arguments: expected 0, got 1

**Comment by JingMatrix** [comment]
It seems that maybe you didn't fully restart Chrome.
Can you restart it, by stopping the app first, and then show me the log?
Thanks for interest in testing it.

**Comment by chuwza** [comment]
> It seems that maybe you didn't fully restart Chrome. Can you restart it, by stopping the app first, and then show me the log? Thanks for interest in testing it.

I have fully restarted chrome but it still shows the error

----part 5 start----

[ 2023-02-17T11:58:56.604 10172: 24802: 24802 I/LSPosed-Bridge | Loading

module cc.aoeiuv020.iamnotdisabled.hook from /data/app/--4yevAITBITTSVKJWg2YTzg==/

cc.aoeiuv020.iamnotdisabled.hook-JSDQhZWU-109YrnfgEJUGA==/base.apk [ 2023-02-17T11:58:56,608 10172: 24802: 24802 I/LSPosed-Bridge Loading class

cc.aoeiuv020.iamnotdisabled.hook.MainHook

| 2023-02-17T11:58:56.610 10172: 24802: 24802 I/LSPosed-

Bridge initZygote: /data/app/--4yevAITBITTSVkJwg2YTzg==/

cc.aoeiuv020.iamnotdisabled.hook-JSDQh2WU-109YrnfgEJUGA==/base.apk [ 2023-02-17T11:58:56.619 10172: 24802: 24802 I/LSPosed-Bridge Loading

module org.matrix. chromext from /data/app/--BOU9yTWU EUMSMKPTbY3Vw==/ org.matrix.chromext-OrAsOmsZg1W7SV6f4coGeA==/base.apk

[ 2023-02-17T11:58:56.621

[2023-02-17T11:58:56.685 10172: 24802: 24802 I/LSPosed-Bridge 1

10172: 24802: 24802 I/LSPosed-Bridge 1 Loading class org.matrix.chromext.MainHook

handleLoadPackage: com.android.chrome [ 2023-02-17T11:58:57.900 10172: 24896: 24896 I/LSPosed-Bridge 1 Loading

module cc.aceiuv020.iamnotdisabled.hook from /data/app/--4yevAITBITTSVKJWg2YTzg==/

11

cc.aoeiuv020.iamnotdisabled.hook-JSDQh2WU-109YrnfgEJUGA==/base.apk [ 2023-02-17T11:58:57.904 10172: 24896: 24896 I/LSPosed-Bridge]

cc.aoeiuv020.iamnotdisabled.hook.MainHook

[2023-02-17T11:58:57.907 10172: 24896; 24896 I/LSPosed-

Bridge initZygote: /data/app/--4yevAITBITTSVKJWg2YTzg==/

+

自

cc.aoeiuv020.iamnotdisabled.hook-JSDQh2WU-109YrnfgEJUGA==/base.apk 2023-02-17T11:58:57.917 10172: 24896: 24896 I/LSPosed-Bridge] Loading module org.matrix. chromext from /data/app/--BOU9yTWU EUMSMKPTbY3Vw==/

org.matrix.chromext-0rAs0msZg1W7SV6f4coGeA==/base.apk

日志

[2023-02-17T11:58:57.919 10172: 24896: 24896 I/LSPosed-Bridge ] Loading class org.matrix.chromext.MainHook

[2023-02-17T11:58:57.983 10172: 24896: 24896 I/LSPosed-Bridge 1 handleLoadPackage: com.android.chrome: privileged_processo

[2023-02-17T11:59:00.308 10172: 24802: 24802 I/LSPosed-Bridge 1

java.lang.IllegalArgumentException: Wrong number of arguments; expected 0, got 1

[2023-02-17T11:59:02.481 10172: 24802: 24802 I/LSPosed-Bridge ]

java.lang.IllegalArgumentException: Wrong number of arguments; expected 0, got 1

**Comment by JingMatrix** [comment]
I believe it is working if you are using the latest Chrome. :)
