### ISSUE TITLE
Installed but unable to use

### ISSUE THREAD

**Issue by xAffan** [JingMatrix/ChromeXt#26]
Hello, I have installed this module. It shows up as installed as in the development settings, I can see the option of eruda. However, in the frontend it is marked as not installed. 

> Here is log, if there is better method to take log, lmk.
[LSPosed_2023-03-26T14_16_56.710216.zip](https://github.com/JingMatrix/ChromeXt/files/11071192/LSPosed_2023-03-26T14_16_56.710216.zip)

**Comment by JingMatrix** [comment]
Hello!
Did you install the newest version from [Github Action](https://github.com/JingMatrix/ChromeXt/actions)?
Could you please also tell me your Chrome version?
Please try to update both of them, and then tell me if they work as expected.

**Comment by xAffan** [comment]
ChromeXT is installed from Github Actions. Chrome version is 111.0.5563.115
Both are already up to date and do not work as expected.

**Comment by JingMatrix** [comment]
I guess your Chrome is installed from APK file, is that true?
I will fix the issue soon.

**Comment by xAffan** [comment]
Nope, it was installed by play store. I am not sure why this happens to be honest.

**Comment by JingMatrix** [comment]
That is very strange. I may be unable to help.
It wil be helpful, if you know how to do it, connect your phone with computer using USB; enable 'USB debug'; and run command `adb logcat -s ChromeXt:D` to see if you get something useful.
This command shows logs like this:
```
03-26 14:14:06.299 17165 17165 I ChromeXt: Get Chrome: com.android.chrome, v111.0.5563.115, split
03-26 14:14:06.311 17165 17165 I ChromeXt: Inited hook: UserScriptHook
03-26 14:14:06.314 17165 17165 I ChromeXt: Inited hook: GestureNavHook
03-26 14:14:06.336 17165 17165 I ChromeXt: Inited hook: MenuHook
03-26 14:14:06.337 17165 17165 I ChromeXt: Inited hook: IntentHook
03-26 14:14:06.904 17293 17293 I ChromeXt: Get Chrome: com.android.chrome, v111.0.5563.115, split
...
```

I am using the same versions as you, but cannot really reproduce your problem.

**Comment by xAffan** [comment]
130|:/ # logcat -s ChromeXt:D                           --------- beginning of main                             03-26 17:25:24.704   490   490 I ChromeXt: Get Chrome: com.android.chrome, v111.0.5563.115, split               03-26 17:25:24.712   490   490 E ChromeXt: java.lang.NoSuchMethodException                                      03-26 17:25:24.712   490   490 E ChromeXt:      at s.b.b(Unknown Source:106)                                    03-26 17:25:24.712   490   490 E ChromeXt:      at p.l.a(Unknown Source:51)                                     03-26 17:25:24.712   490   490 E ChromeXt:      at org.matrix.chromext.MainHook.a(Unknown Source:17)            03-26 17:25:24.712   490   490 E ChromeXt:      at org.matrix.chromext.b.c(Unknown Source:61)                   03-26 17:25:24.712   490   490 E ChromeXt:      at org.matrix.chromext.b.b(Unknown Source:10)                   03-26 17:25:24.712   490   490 E ChromeXt:      at s.c.afterHookedMethod(Unknown Source:39)                     03-26 17:25:24.712   490   490 E ChromeXt:      at de.robv.android.xposed.XposedBridge$AdditionalHookInfo.callback(Unknown Source:147)                                  03-26 17:25:24.712   490   490 E ChromeXt:      at LSPHooker_.attachBaseContext(Unknown Source:11)              03-26 17:25:24.712   490   490 E ChromeXt:      at android.app.Application.attach(Application.java:333)         03-26 17:25:24.712   490   490 E ChromeXt:      at android.app.Instrumentation.newApplication(Instrumentation.java:1179)                                                03-26 17:25:24.712   490   490 E ChromeXt:      at android.app.LoadedApk.makeApplication(LoadedApk.java:1369)   03-26 17:25:24.712   490   490 E ChromeXt:      at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7063)                                           03-26 17:25:24.712   490   490 E ChromeXt:      at android.app.ActivityThread.access$1600(ActivityThread.java:271)                                                      03-26 17:25:24.712   490   490 E ChromeXt:      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2134)                                                 03-26 17:25:24.712   490   490 E ChromeXt:      at android.os.Handler.dispatchMessage(Handler.java:106)         03-26 17:25:24.712   490   490 E ChromeXt:      at android.os.Looper.loopOnce(Looper.java:210)                  03-26 17:25:24.712   490   490 E ChromeXt:      at android.os.Looper.loop(Looper.java:299)                      03-26 17:25:24.712   490   490 E ChromeXt:      at android.app.ActivityThread.main(ActivityThread.java:8309)    03-26 17:25:24.712   490   490 E ChromeXt:      at java.lang.reflect.Method.invoke(Native Method)               03-26 17:25:24.712   490   490 E ChromeXt:      at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:556)                                    03-26 17:25:24.712   490   490 E ChromeXt:      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1038)03-26 17:25:24.717   490   490 I ChromeXt: Inited hook: f                                                       03-26 17:25:24.729   490   490 I ChromeXt: Inited hook: k                                                       03-26 17:25:24.731   490   490 I ChromeXt: Inited hook: g                                                       03-26 17:25:25.714   824   824 I ChromeXt: Get Chrome: com.android.chrome, v111.0.5563.115, split               03-26 17:25:25.722   824   824 E ChromeXt: java.lang.NoSuchMethodException                                      03-26 17:25:25.722   824   824 E ChromeXt:      at s.b.b(Unknown Source:106)                                    03-26 17:25:25.722   824   824 E ChromeXt:      at p.l.a(Unknown Source:51)                                     03-26 17:25:25.722   824   824 E ChromeXt:      at org.matrix.chromext.MainHook.a(Unknown Source:17)            03-26 17:25:25.722   824   824 E ChromeXt:      at org.matrix.chromext.b.c(Unknown Source:61)                   03-26 17:25:25.722   824   824 E ChromeXt:      at org.matrix.chromext.b.b(Unknown Source:10)                   03-26 17:25:25.722   824   824 E ChromeXt:      at s.c.afterHookedMethod(Unknown Source:39)                     03-26 17:25:25.722   824   824 E ChromeXt:      at de.robv.android.xposed.XposedBridge$AdditionalHookInfo.callback(Unknown Source:147)                                  03-26 17:25:25.722   824   824 E ChromeXt:      at LSPHooker_.attachBaseContext(Unknown Source:11)              03-26 17:25:25.722   824   824 E ChromeXt:      at android.app.Application.attach(Application.java:333)         03-26 17:25:25.722   824   824 E ChromeXt:      at android.app.Instrumentation.newApplication(Instrumentation.java:1179)                                                03-26 17:25:25.722   824   824 E ChromeXt:      at android.app.LoadedApk.makeApplication(LoadedApk.java:1369)   03-26 17:25:25.722   824   824 E ChromeXt:      at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7063)                                           03-26 17:25:25.722   824   824 E ChromeXt:      at android.app.ActivityThread.access$1600(ActivityThread.java:271)                                                      03-26 17:25:25.722   824   824 E ChromeXt:      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2134)                                                 03-26 17:25:25.722   824   824 E ChromeXt:      at android.os.Handler.dispatchMessage(Handler.java:106)         03-26 17:25:25.722   824   824 E ChromeXt:      at android.os.Looper.loopOnce(Looper.java:210)                  03-26 17:25:25.722   824   824 E ChromeXt:      at android.os.Looper.loop(Looper.java:299)                      03-26 17:25:25.722   824   824 E ChromeXt:      at android.app.ActivityThread.main(ActivityThread.java:8309)    03-26 17:25:25.722   824   824 E ChromeXt:      at java.lang.reflect.Method.invoke(Native Method)               03-26 17:25:25.722   824   824 E ChromeXt:      at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:556)                                    03-26 17:25:25.722   824   824 E ChromeXt:      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1038)03-26 17:25:25.729   824   824 I ChromeXt: Inited hook: f                                                       03-26 17:25:25.748   824   824 I ChromeXt: Inited hook: k                                                       03-26 17:25:25.749   824   824 I ChromeXt: Inited hook: g                                                       03-26 17:25:26.767   490   490 E ChromeXt: java.lang.NoSuchMethodException                                      03-26 17:25:26.767   490   490 E ChromeXt:      at s.b.f(Unknown Source:64)                                     03-26 17:25:26.767   490   490 E ChromeXt:      at q.j.d(Unknown Source:20)                                     03-26 17:25:26.767   490   490 E ChromeXt:      at q.j.c(Unknown Source:2)                                      03-26 17:25:26.767   490   490 E ChromeXt:      at p.i.c(Unknown Source:202)                                    03-26 17:25:26.767   490   490 E ChromeXt:      at p.i.b(Unknown Source:22)                                     03-26 17:25:26.767   490   490 E ChromeXt:      at s.c.beforeHookedMethod(Unknown Source:16)                    03-26 17:25:26.767   490   490 E ChromeXt:      at de.robv.android.xposed.XposedBridge$AdditionalHookInfo.callback(Unknown Source:79)                                   03-26 17:25:26.767   490   490 E ChromeXt:      at LSPHooker_.q(Unknown Source:28)                              03-26 17:25:26.767   490   490 E ChromeXt:      at Of.m(chromium-TrichromeChromeGoogle.aab-stable-556311533:212)03-26 17:25:26.767   490   490 E ChromeXt:      at Df.j(chromium-TrichromeChromeGoogle.aab-stable-556311533:175)03-26 17:25:26.767   490   490 E ChromeXt:      at wf.a(chromium-TrichromeChromeGoogle.aab-stable-556311533:9)  03-26 17:25:26.767   490   490 E ChromeXt:      at wf.onTouch(chromium-TrichromeChromeGoogle.aab-stable-556311533:37)                                                   03-26 17:25:26.767   490   490 E ChromeXt:      at android.view.View.dispatchTouchEvent(View.java:14847)        03-26 17:25:26.767   490   490 E ChromeXt:      at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3131)                                            03-26 17:25:26.767   490   490 E ChromeXt:      at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2755)                                                       03-26 17:25:26.767   490   490 E ChromeXt:      at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3131)                                            03-26 17:25:26.767   490   490 E ChromeXt:      at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2755)                                                       03-26 17:25:26.767   490   490 E ChromeXt:      at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3131)                                            03-26 17:25:26.767   490   490 E ChromeXt:      at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2755)                                                       03-26 17:25:26.767   490   490 E ChromeXt:      at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3131)                                            03-26 17:25:26.767   490   490 E ChromeXt:      at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2755)                                                       03-26 17:25:26.767   490   490 E ChromeXt:      at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3131)                                            03-26 17:25:26.767   490   490 E ChromeXt:      at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2755)                                                       03-26 17:25:26.767   490   490 E ChromeXt:      at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3131)                                            03-26 17:25:26.767   490   490 E ChromeXt:      at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2755)                                                       03-26 17:25:26.767   490   490 E ChromeXt:      at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3131)                                            03-26 17:25:26.767   490   490 E ChromeXt:      at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2755)                                                       03-26 17:25:26.767   490   490 E ChromeXt:      at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3131)                                            03-26 17:25:26.767   490   490 E ChromeXt:      at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2755)                                                       03-26 17:25:26.767   490   490 E ChromeXt:      at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3131)                                            03-26 17:25:26.767   490   490 E ChromeXt:      at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2755)                                                       03-26 17:25:26.767   490   490 E ChromeXt:      at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3131)                                            03-26 17:25:26.767   490   490 E ChromeXt:      at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2755)                                                       03-26 17:25:26.767   490   490 E ChromeXt:      at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3131)                                            03-26 17:25:26.767   490   490 E ChromeXt:      at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2755)                                                       03-26 17:25:26.767   490   490 E ChromeXt:      at com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:570)                                    03-26 17:25:26.767   490   490 E ChromeXt:      at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1895)                               03-26 17:25:26.767   490   490 E ChromeXt:      at android.app.Activity.dispatchTouchEvent(Activity.java:4283)  03-26 17:25:26.767   490   490 E ChromeXt:      at ad.f(chromium-TrichromeChromeGoogle.aab-stable-556311533:3)  03-26 17:25:26.767   490   490 E ChromeXt:      at ad.dispatchTouchEvent(chromium-TrichromeChromeGoogle.aab-stable-556311533:1)                                         03-26 17:25:26.767   490   490 E ChromeXt:      at java.lang.reflect.Method.invoke(Native Method)               03-26 17:25:26.767   490   490 E ChromeXt:      at ug.invoke(chromium-TrichromeChromeGoogle.aab-stable-556311533:66)                                                    03-26 17:25:26.767   490   490 E ChromeXt:      at java.lang.reflect.Proxy.invoke(Proxy.java:1006)              03-26 17:25:26.767   490   490 E ChromeXt:      at $Proxy2.dispatchTouchEvent(Unknown Source)                   03-26 17:25:26.767   490   490 E ChromeXt:      at com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:528)                                         03-26 17:25:26.767   490   490 E ChromeXt:      at android.view.View.dispatchPointerEvent(View.java:15115)      03-26 17:25:26.767   490   490 E ChromeXt:      at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:6663)                          03-26 17:25:26.767   490   490 E ChromeXt:      at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:6458)                                    03-26 17:25:26.767   490   490 E ChromeXt:      at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5901)                                                 03-26 17:25:26.767   490   490 E ChromeXt:      at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5958)                                         03-26 17:25:26.767   490   490 E ChromeXt:      at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:5924)                                                 03-26 17:25:26.767   490   490 E ChromeXt:      at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:6089)                                            03-26 17:25:26.767   490   490 E ChromeXt:      at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:5932)                                                   03-26 17:25:26.767   490   490 E ChromeXt:      at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:6146)                                              03-26 17:25:26.767   490   490 E ChromeXt:      at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5905)                                                 03-26 17:25:26.767   490   490 E ChromeXt:      at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5958)                                         03-26 17:25:26.767   490   490 E ChromeXt:      at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:5924)                                                 03-26 17:25:26.767   490   490 E ChromeXt:      at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:5932)                                                   03-26 17:25:26.767   490   490 E ChromeXt:      at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5905)                                                 03-26 17:25:26.767   490   490 E ChromeXt:      at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:8906)                                                  03-26 17:25:26.767   490   490 E ChromeXt:      at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:8857)                                               03-26 17:25:26.767   490   490 E ChromeXt:      at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:8825)                                                  03-26 17:25:26.767   490   490 E ChromeXt:      at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:9042)                              03-26 17:25:26.767   490   490 E ChromeXt:      at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:281)                                      03-26 17:25:26.767   490   490 E ChromeXt:      at android.os.MessageQueue.nativePollOnce(Native Method)        03-26 17:25:26.767   490   490 E ChromeXt:      at android.os.MessageQueue.next(MessageQueue.java:340)          03-26 17:25:26.767   490   490 E ChromeXt:      at android.os.Looper.loopOnce(Looper.java:168)                  03-26 17:25:26.767   490   490 E ChromeXt:      at android.os.Looper.loop(Looper.java:299)                      03-26 17:25:26.767   490   490 E ChromeXt:      at android.app.ActivityThread.main(ActivityThread.java:8309)    03-26 17:25:26.767   490   490 E ChromeXt:      at java.lang.reflect.Method.invoke(Native Method)               03-26 17:25:26.767   490   490 E ChromeXt:      at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:556)                                    03-26 17:25:26.767   490   490 E ChromeXt:      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1038)

**Comment by xAffan** [comment]
The previous reply is a mess. Here is a txt.
[twat.txt](https://github.com/JingMatrix/ChromeXt/files/11071560/twat.txt)

**Comment by JingMatrix** [comment]
Thank you very much.
As you can see, some important information are obscured (I should have realized it).
Could you provide logs with a debug version of `ChromeXt`?
To install a debug version, you need to uninstall the original `ChromeXt`, here is to the apk to install:
[debug_version.zip](https://github.com/JingMatrix/ChromeXt/files/11071645/debug_version.zip)

If this debug version happens to work, you can keep using it. The debug version just being a bit larger in size than the slimmed release version on Github.

**Comment by xAffan** [comment]
Hello, the debug version works. Do you still want the log or something? If not, please close the issue. And thanks.

**Comment by JingMatrix** [comment]
Okay, happy to know it works. Have a nice day!
