### ISSUE TITLE
module doesn't work

### ISSUE THREAD

**Issue by xushet** [JingMatrix/ChromeXt#28]
Chrome version
 111.0.5563.116（Google Play）

ChromeXt version
2.1.0

 Lsposed  version
 1.8.6 (6857)

 system version
 11 (API 30)

equipment
 Xiaomi Mi 6

 system structure
 arm64-v8a

Script
https://greasyfork.org/zh-CN/scripts/438684-pagetual

Follow the instructions, click the Chrome menu to download the script, and open it as a text browser after the download is complete, instead of installing the script

![Screenshot_20230402-105342_Pixelated_Launcher.png](https://user-images.githubusercontent.com/34502902/229328508-4241ee89-8c45-4913-9101-f740cb65dcf6.png)

**Comment by JingMatrix** [comment]
I tested your script and installed it without problem. By the way, you
don't need to download this one before installing it.
Are you using the latest build of ChromeXt from GitHub Action?
And do you see any error log from your Xposed framework?

**Comment by xushet** [comment]
> I tested your script and installed it without problem. By the way, you
> don't need to download this one before installing it.
> Are you using the latest build of ChromeXt from GitHub Action?
> And do you see any error log from your Xposed framework?
> 

![Screenshot_20230402-121155_LSPosed.png](https://user-images.githubusercontent.com/34502902/229330931-682d51c7-7f68-4d36-8729-af4c7f2b855b.png)

**Comment by xushet** [comment]
Tried uninstalling and reinstalling, still browsing in text format![Screenshot_20230402-121654_Pixelated_Launcher.png](https://user-images.githubusercontent.com/34502902/229331080-43a1a19d-2aff-4a13-805c-fbb273dac169.png)

**Comment by JingMatrix** [comment]
I still cannot reproduce your problem.
Can you please try my remark to this issue?
https://github.com/JingMatrix/ChromeXt/issues/26#issuecomment-1484090938

**Comment by xushet** [comment]
> I still cannot reproduce your problem.
> Can you please try my remark to this issue?
> https://github.com/JingMatrix/ChromeXt/issues/26#issuecomment-1484090938

good it works！![Screenshot_20230402-232038_Pixelated_Launcher.png](https://user-images.githubusercontent.com/34502902/229362742-9cfd9573-5a17-4932-bcf8-06bb1bb42cac.png)
