### ISSUE TITLE
Support for Chrome v112 Update

### ISSUE THREAD

**Issue by MohamadBayz** [JingMatrix/ChromeXt#31]
The module works but I can't install any scripts, install prompt doesn't show.
Do you need log or v12 not supported yet?

**Comment by JingMatrix** [comment]
I didn't receive v112 update from Google play yet, so I haven't tried.
Did you try the lasted build? In the last two commits, I tried to make the module indpendent of Chrome versions.

**Comment by MohamadBayz** [comment]
> Did you try the latest build? 

I did try it but still no prompt for installing scripts.

**Comment by JingMatrix** [comment]
I will have more information when I get the update.

Just for now, does it fail for any scripts installing or just a specific one?

**Comment by MohamadBayz** [comment]
It fails for Any script. First i did had Two of my scripts pre installed in the frontend but they didn't work so i removed them then tried to install a new one but failed.

**Comment by JingMatrix** [comment]
This particular bug is fixed just now, but the support of v112 is not finished yet.

**Comment by MohamadBayz** [comment]
Going to test it then. Well done 👍

**Comment by JingMatrix** [comment]
Now the module should support Chrome versions till v114, as I just tested.
Only gesture navigation feature is not full supported.
