### ISSUE TITLE
[Request] Excellent module! Can you expand its scope to Brave browser.

### ISSUE THREAD

**Issue by iamMG** [JingMatrix/ChromeXt#32]
I discovered this xposed module today, and I am blown away by it! 
It sucks that I don't use Chrome as my daily driver, but [Brave](https://play.google.com/store/apps/details?id=com.brave.browser&hl=en&gl=US). 
Would it possible to port the module so that it runs on Brave as well? That would be really useful for tons of people!

**Comment by JingMatrix** [comment]
Now Brave is supported, please try the lastest build from [Github Action](https://github.com/JingMatrix/ChromeXt/actions).
If you encounter bugs, don't hesitate to report.
I am not using Brave for daily life, so there might exist some unnoticed bugs.

**Comment by iamMG** [comment]
Thanks for the quick update. The module is working with Brave.
I even underwent a (big) problem straight away. I was playing around with the Eruda console and ended up hiding elements on the Google search results page. I don't how to revert the settings. Had to uninstall the ChromeXT module.

**Comment by JingMatrix** [comment]
The setting is in the `Resources` panel, where you can find your saved filters and delete them as you want.

By the way, a bug is fixed in the lastest version. Please consider update to it.

**Comment by iamMG** [comment]
Thanks for the tip. Issue is resolved now.

And yes I updated the app. 

Can you also add the [Brave Beta](https://play.google.com/store/apps/details?id=com.brave.browser_beta) browser in tue scope?

**Comment by JingMatrix** [comment]
Now, Brave Beta is added into the scope.
