### ISSUE TITLE
Add Support For More APIs

### ISSUE THREAD

**Issue by MohamadBayz** [JingMatrix/ChromeXt#33]
Hi, i Have a Particular Script That Requires Some API Which is Not Supported by Chrome XT Unfortunately and I'm asking to support them.

Required APIs:
grant (GM_getValue, GM_setValue, GM_addValueChangeListener, GM_registerMenuCommand, GM_download)

**Comment by JingMatrix** [comment]
Tell me the script and describe which important function is missing particularly.
Those APIs are too hard to support, I would like to give partial support to solve particular problems.

**Comment by MohamadBayz** [comment]
This script in particular
https://greasyfork.org/en/scripts/427320-imdb-quick-search

Also this script 
https://github.com/FarisHijazi/Rarbg-Enhancer-UserScript

**Comment by JingMatrix** [comment]
The first script is now running well.

The second one is running, but its function may not work since Android Chrome doesn't support `@require` from `https://raw.githubusercontent.com`.

**Comment by JingMatrix** [comment]
As a solution, you may ask the original author to follow this advice: https://github.com/orgs/community/discussions/25343

**Comment by MohamadBayz** [comment]
First script works like a charm, as for the second one I contacted the author and waiting for an answer. So for now (hopefully for ever) my issue is solved.
Thanks for the amazing respond for issues and question. Great support! Keep up the good work.

**Comment by JingMatrix** [comment]
Thanks for your comments!

The second script is now working as well.
You may need to reinstall the script (due to a bug in the front-end part).

The script is consuming a lot of RAM. (Persionally, I conjecture there is better way to remove AD redirections.)
This makes ChromeXt not ideal for this script.

**Comment by JingMatrix** [comment]
I write a simple script removing all ADs there by blocking javascripts:
```javascript
// ==UserScript==
// @name	Disable ADS - Rarbg
// @namespace	JingMatrix
// @match	https://rarbgunblocked.org/*
// @run-at	document-start
// ==/UserScript==

const meta = document.createElement("meta");
meta.setAttribute("http-equiv", "Content-Security-Policy");
meta.setAttribute("content", "script-src 'none'");
try {
  document.head.append(meta);
} catch {
  setTimeout(() => {
    document.head.append(meta);
  }, 0);
}
````

It works perferctly for ChromeXt, not sure for other userscript engines.
It seems there is no need to enter CAPTCHA neither.
To install it, you save it to your phone with a name like `rarbg.user.js` and open it with ChromeXt.
You may ask the original author to adopt it.

**Comment by MohamadBayz** [comment]
But wouldn't disabling JavaScript  cause some down sides? Like Limits the website's functions?

**Comment by MohamadBayz** [comment]
Also i didn't understand this

>It seems there is no need to enter CAPTCHA neither.

So does the script bypass the captcha or the captcha is disabled?

**Comment by JingMatrix** [comment]
I think the captcha is disabled.
That website could run with javascript, you need to try and see how it looks.

**Comment by MohamadBayz** [comment]
Captcha isn't disabled but there's no ads and the website works simple and fast

**Comment by MohamadBayz** [comment]
Mainly i use the script for the captcha solver it makes using the website easier
The author published a standalone script for the captcha solver but i guess i can't use it with JavaScript disabled

**Comment by MohamadBayz** [comment]
Beside the script works great now it's Supported! 👍

**Comment by MohamadBayz** [comment]
Hi! This script has every supported API and yet doesn't work, can you check it please
https://greasyfork.org/en/scripts/388069-subscene-url-search/code

**Comment by JingMatrix** [comment]
Fixed, it was url matching problem.

**Comment by MohamadBayz** [comment]
> Fixed, it was url matching problem.

👏🔥 Thanks

**Comment by JingMatrix** [comment]
>  Thanks

@MohamadBayz , I also appreciate your help of finding and reporting bugs.
You are contributing to the project to make it better, that is very nice.

**Comment by MohamadBayz** [comment]
I'm loving this project and Happy to help in any way possible.

**Comment by MohamadBayz** [comment]
Hi again! A usersctipt I'm trying to use has `@Grant None` API and it's not supported. Can you check it?
https://greasyfork.org/en/scripts/416491-redirect-to-high-res-image

**Comment by JingMatrix** [comment]
It is the problem of the matching urls.
My code requires the matching url to include `://` to start macthing.
You can edit the matching rules in the front-end.

**Comment by MohamadBayz** [comment]
U r right sorry for my ignorance I didn't notice that. Thanks
