### ISSUE TITLE
[Suggestion] Edge support?

### ISSUE THREAD

**Issue by gaussandhisgun** [JingMatrix/ChromeXt#35]
Since Microsoft Edge for android is also chromium, the only real problem would be the way Microsoft did the menu thing - but then again, you could just shove the control buttons somewhere else, i guess?

**Comment by JingMatrix** [comment]
Nice suggestion, I will try it.

**Comment by JingMatrix** [comment]
The menu needs more work, currently one is able to use UserScripts.
