### ISSUE TITLE
Bromite does not work for some reason

### ISSUE THREAD

**Issue by gaussandhisgun** [JingMatrix/ChromeXt#36]
Device: Redmi Note 9S
ROM: Project Blaze 2.5
Android version: 13
Bromite: org.bromite.bromite
Bromite version: 108.0.5359.156 (F-Droid)

Confirmed to work on Chrome 112.0.5615.135 from Playstore.

**Comment by JingMatrix** [comment]
Do you have some relevant logs for bromite?

**Comment by gaussandhisgun** [comment]
No, but I can get some if you tell me where to look.

**Comment by JingMatrix** [comment]
If you are using LSPosed, in the application there is a panel showing the logs and you have option to save it.

**Comment by gaussandhisgun** [comment]
Whatever it was, it got fixed with the latest extension update. Thanks.
