### ISSUE TITLE
Userscript configurations for mixing tabs (incognito mode and normal mode)

### ISSUE THREAD

**Issue by MohamadBayz** [JingMatrix/ChromeXt#38]
Hi! Userscript's settings and configurations aren't global meaning in incognito mode they are back to default settings also opening front end in Normal mode when incognito mode is active won't show ChromeXT installed but instead you have to open the front end in incognito mode as well

**Comment by JingMatrix** [comment]
Sorry, I didn't get your point.
Could you explain to how to reproduce the problem you encountered?

**Comment by MohamadBayz** [comment]
While incognito tab is active I can't open the front end in Normal tab (says ChromeXT isn't installed) instead i have to open it in incognito tab

**Comment by JingMatrix** [comment]
> i saw that the script's settings went back to default settings. 
I think this is the desired behaviour, in incognito mode, everything is tempeoray. And I don't have easy way to change it either.

**Comment by MohamadBayz** [comment]
Better example:
Another script i configured in the front end added a website to it's @match API it worked but going to incognito it doesn't work there it shows my added website in the front end but doesn't function in that website

**Comment by JingMatrix** [comment]
> but going to incognito it doesn't work there it shows my added website in the front end but doesn't function in that website

I see, mixing tabs is buggy.

**Comment by MohamadBayz** [comment]
One Extra Note:
If incognito is active you can't install Userscripts in Normal tab.
Related bug as well.

**Comment by JingMatrix** [comment]
Bug fixed now.

**Comment by MohamadBayz** [comment]
Wow the speed! Thanks.
