### ISSUE TITLE
Add Webview Support

### ISSUE THREAD

**Issue by moya2162** [JingMatrix/ChromeXt#39]
Please consider adding webview support to project scope if possible. I tried using this on Mulch Webview but it did not work.

**Comment by JingMatrix** [comment]
Can you explain why you would like to use Webview instead of the Mulch browser?

**Comment by JingMatrix** [comment]
I get your idea. Which lightweight browser you are using?
A first thing I need is an app to debug, and one cannot directly open System Webview.
As an opinion, I think there is barely no need to use an indenpent Webview such as Mulch Webview. It seems nothing needs to change for System Webview, as least to me.

**Comment by JingMatrix** [comment]
Ok, I get it, the support won't be difficult.
But maybe only UserScript function will be implement.
It takes time to work on it, and won't be done soon.
Webview is different from chromium browser, it almost requires write a new module.

**Comment by moya2162** [comment]
No worries. I thought webview was similar to Chromium since Bromite and Mulch both offer webview alternatives. If it makes sense to make a new module. I will keep eye out with whatever you decide to do.

Thank you for extremely fast response and clear communication. Best wishes!

**Comment by JingMatrix** [comment]
Now I am sure that it is impossible to hook Webview and achieve what you want.

Here is a reminder for possible interests of any visitors.
Run `frida-ps -U | grep web`, we get
```
16078  com.google.android.webview:sandboxed_process0:org.chromium.content.app.SandboxedProcessService0:0
16358  com.google.android.webview:sandboxed_process0:org.chromium.content.app.SandboxedProcessService0:0
16114  com.google.android.webview:webview_service                                                       
 2241  webview_zygote 
```
Run `frida-trace -U -j 'org.*!*' 16358` to hook a webview:sandboxed_process above, but we get no interesting function calls.
Xposed hooks simply fail since no embedded classes will be called.

**Comment by JingMatrix** [comment]
`Fulguris Browser` is now partially supoorted, ` Privacy Browser` is not supported due to unknown reason.

**Comment by JingMatrix** [comment]
Now webview based browsers are fully supported.

**Comment by moya2162** [comment]
Thought you had abandoned the idea of adding webview support. Cool to see you have figured out a solution. Is your solution general or app specific?

**Comment by JingMatrix** [comment]
It is general. If not applied to your app, please tell me.
