### ISSUE TITLE
Not able to use Eruda Console if cookies are disabled in Bromite

### ISSUE THREAD

**Issue by Sdarfeesh** [JingMatrix/ChromeXt#43]

**Comment by JingMatrix** [comment]
For all websites or just one site, please give the example.

And how do you disable cookies?

**Comment by JingMatrix** [comment]
If it doesn't bother you too much, please consider only block third party cookies for now.

**Comment by Sdarfeesh** [comment]
> For all websites or just one site, please give the example.
> 
> And how do you disable cookies?


https://github.com/JingMatrix/ChromeXt/assets/50188628/d4d39d78-327d-4440-ab00-577ef163cef9

**Comment by JingMatrix** [comment]
Block all cookies means blocking any persistent data, but Eruda cannot work witthout writing to localStorage.
If you want to use Eruda on a site, you should choose `Block all cookies`.
