### ISSUE TITLE
Not loading on Background Tabs

### ISSUE THREAD

**Issue by MohamadBayz** [JingMatrix/ChromeXt#48]
When opening a tab in the background if you don't go to the background tab immediately, Chromext won't load (Usersctipts & Eruda Element Hiding) on that tab until you reload the page although if you go immediately to that tab it will load.
Let me explain further by a screen recording example:
In the screen recording pay attention to the highlighted section in my first attempt when i open a tab in the background and I open it immediately it loads hiding element just fine as you can see it hides the "Open App" Element BUT in the second attempt when i wait a little bit before opening the tab it won't load them as you can see there "Open App" Element is shown but if i reload the page then it will load the hiding element as well as the usersctipt on that page.
https://photos.app.goo.gl/fqQ1xJiWRRK65nVh8

**Comment by JingMatrix** [comment]
Thanks for reporting, it is fixed now :smile:

**Comment by MohamadBayz** [comment]
Wow! That fast! 💥
Thank you 👍
