### ISSUE TITLE
Running UserScripts Indicator 

### ISSUE THREAD

**Issue by MohamadBayz** [JingMatrix/ChromeXt#49]
I got a suggestion that might be interesting to add
• Add an indicator in the page menu that indicates which Usersctipts are running on that page.

**Comment by MohamadBayz** [comment]
Another suggestion that might not be really important :)
Is to create a Community so users could join and ask questions through ideas report bugs, not all normal users can use GitHub for reporting bugs and asking questions so this could be a useful thing for making ChromeXt closer to users

**Comment by JingMatrix** [comment]
An indicator might be crowded in the page menu. How about showing it in the Eruda panel?

**Comment by MohamadBayz** [comment]
That's even better actually, could be in the Recourse Page above the page's scripts, maybe?

**Comment by JingMatrix** [comment]
This is now implemented in the `Info` panel, check it out.
