### ISSUE TITLE
Invalid Script

### ISSUE THREAD

**Issue by MohamadBayz** [JingMatrix/ChromeXt#5]
This script worked before when ChromeXT first released but know when i try to install it it says "Invalid Script" and it's because of the first line of the script as it has
```
// prettier-ignore
var meta = {
    rawmdb: function () {
```
In the first line
The script link
https://raw.githubusercontent.com/FarisHijazi/Rarbg-Enhancer-UserScript/master/Rarbg-Enhancer-UserScript.user.js
See attached screenshot 
![Screenshot_20221220-075230_Chrome](https://user-images.githubusercontent.com/63660736/208592087-aac4d31c-662a-4937-943d-b29298f2570a.png)

**Comment by JingMatrix** [comment]
You should change the script instead.
You can edit it in the installation interface.

It is your responsibility to ensure that the script being valid before using ChromeXt.

**Comment by MohamadBayz** [comment]
I'm having trouble making this userscript works with ChromeXT. I have tried to make it work but it doesn't seems to work with ChromeXT although it works just fine with tampermonkey and violentmonkey. My guess is prettier ignore function isn't supported or it doesn't work?

**Comment by JingMatrix** [comment]
Maybe you can remove the beginning lines `// pret...` and then remove some lines after the header till the line `meta.window = this;` (included).

Please instead ask the original author for help, this is not an issue of ChromeXt.

**Comment by MohamadBayz** [comment]
I've talked to the author but he couldn't find a solution because he didn't had a rooted Android, and I've tried your suggestion but it didn't work
Anyway I'll be waiting for the author for a workaround

**Comment by MohamadBayz** [comment]
A suggestion can you make ChromeXT ignores any code in the beginning that doesn't start with `// @`? Beside the mentioned Userscript i have had issue with other Userscripts too like [I Don't Care About Cookies](https://github.com/xarantolus/bromite-userscripts/releases/latest/download/idcac.user.js) and  [Cosmetic AdBlock](https://github.com/xarantolus/bromite-userscripts/releases/latest/download/cosmetic.user.js) this might fix invalid Script for other scripts too

**Comment by JingMatrix** [comment]
Ok, no supported.

**Comment by MohamadBayz** [comment]
Ok, now i can install this with newer ChromeXt version but it can't run sadly even i tried using @match

**Comment by JingMatrix** [comment]
It might require knowledge of Javascript and Chrome DevTools to solve the problem by your own. Good luck.

It could be that the @resource API is not implemented yet.

**Comment by MohamadBayz** [comment]
Unfortunately i don't have much of knowledge about java, so Then I'll wait for more api support

**Comment by JingMatrix** [comment]
New APIs are implemented, you might want to try it again.

**Comment by MohamadBayz** [comment]
Unfortunately still not working

**Comment by MohamadBayz** [comment]
Ok, only things that i noticed int the Userscript's API that was missing in ChromeXT was `GM_registerMenuCommand` `GM_download`

**Comment by JingMatrix** [comment]
`GM_download` is not used in the script, `GM_registerMenuCommand` is less likely to have big effects.
