### ISSUE TITLE
Broken on brave 

### ISSUE THREAD

**Issue by androidacy-user** [JingMatrix/ChromeXt#50]
Version: 1.52.126 Chromium: 114.0.5735.133 (Official Build) (64-bit) 

Eruda console does not show in the menu whatsoever. Shows update option in developer options but that's it

**Comment by JingMatrix** [comment]
Fixed by the latest commit, please install it from the github action.

**Comment by JingMatrix** [comment]
Thanks for telling me that.
When SpeedReader becomes stable, there is no need to add reader mode support of it from the side of ChromeXt.

**Comment by JingMatrix** [comment]
I found that it is still possible to use reader mode in Brave, so I add supports to it in the last commit.

**Comment by JingMatrix** [comment]
By the way last time, I introduced a bug into the code so that the Eruda menu is not showing.
Please update to the lastest one in the GitHub Action.
