### ISSUE TITLE
Crash Report

### ISSUE THREAD

**Issue by MohamadBayz** [JingMatrix/ChromeXt#51]
Hi! With the new update whenever i try to open the menu page while a website is loaded chrome crashes with this log:
[crash-com-android-chrome-18-06_09-58-47.zip](https://github.com/JingMatrix/ChromeXt/files/11780813/crash-com-android-chrome-18-06_09-58-47.zip)

**Comment by MohamadBayz** [comment]
By new update i meant Version 3.2

**Comment by MohamadBayz** [comment]
I just checked again. it seems that the crash was caused by LSPosed. LSPosed itself was crashing and after re-flashing it, it fixed it.

**Comment by JingMatrix** [comment]
Yeah, this update changes something, so one needs to restart the browser after updating.

**Comment by MohamadBayz** [comment]
I don't think that was the issue, lately my LSPosed is crashing randomly not sure why and that caused chrome to crash

**Comment by JingMatrix** [comment]
Okay, that could be possible. You can report it to LSPosed when it becomes not random :smile:

**Comment by MohamadBayz** [comment]
Will do, thanks
