### ISSUE TITLE
Eruda Console auto disables 

### ISSUE THREAD

**Issue by MohamadBayz** [JingMatrix/ChromeXt#52]
Hi! Eruda console gets Disabled after jumping to other pages. Any way to make it stays shown after jumping to other pages? :)

**Comment by JingMatrix** [comment]
Could you explain why would you like to have this feature? What do you do with it?

Depending on your needs, it might be possible.

**Comment by MohamadBayz** [comment]
Network request:
Some websites loads let's say files/medias when the page loads so it's impossible to catch those file/media(s) if Eruda console keeps restarting with the webpage.

**Comment by JingMatrix** [comment]
This is technically impossible for Eruda.
Consider using `Developer Tools` from the ChromeXt front-end.
Actually, eruda is just a baby and simple version of developer tools.
By contrast, developer tools is very powerful, one can even [modify response headers](https://developer.chrome.com/docs/devtools/overrides/) using it.

**Comment by MohamadBayz** [comment]
I wasn't really aware that ChromeXt Has `Developer Tools` it's kinda tricky to find it if someone hasn't read the Readme (or missed it like me). I was using it in Kiwi Browser it was indeed much more effective than Eruda Console. I guess I'll be using it from now on. Thanks for the clarification.

**Comment by JingMatrix** [comment]
Haha, `Developer Tools` is actually the function for which I am pround of `ChromeXt`. You should definitely try it.

**Comment by MohamadBayz** [comment]
I wish i knew more about JavaScript there's so much to do, too many possibilities and Here I'm in the Dark XD
I'll definitely try though

**Comment by HinataKato** [comment]
> This is technically impossible for Eruda. Consider using `Developer Tools` from the ChromeXt front-end. Actually, eruda is just a baby and simple version of developer tools. By contrast, developer tools is very powerful, one can even [modify response headers](https://developer.chrome.com/docs/devtools/overrides/) using it.

I just realized that I need the frontend page to access the more complete Developer tools, maybe adds more hint in readme?

**Comment by JingMatrix** [comment]
@HinataKato It is already a section header in the README. Do you have ideas to improve it?
