### ISSUE TITLE
请求支持360极速浏览器

### ISSUE THREAD

**Issue by zhuxf8** [JingMatrix/ChromeXt#53]
请求支持360极速浏览器，不知道能不能不支持

**Comment by JingMatrix** [comment]
在哪里下载 Android 版？我对它的安全性有些许担忧。

**Comment by zhuxf8** [comment]
> 

https://www.coolapk.com/apk/com.qihoo.contents
这里下载

**Comment by JingMatrix** [comment]
支持不了，它使用了比较复杂的类名混淆技术。
理论上可以破解，但是现实成本太高了。

**Comment by zhuxf8** [comment]
是喔，忘了360的软件都用了360加固。那打扰了，谢谢。
