### ISSUE TITLE
What is the use case of the Module?

### ISSUE THREAD

**Issue by matt873** [JingMatrix/ChromeXt#56]
I want it to post  in discussion section but didn't find so wanted to post it here. I am curious what is the use case of this module. Can someone briefly explain in simple words?

**Comment by JingMatrix** [comment]
For normal users, it is meant to load UserScripts.
For developpers, it is a lightweight replacement of kiwi.

In my daily life, I need it to customize many websites, such as removing Ads, bypassing login barriers and so on.
You may find interesting UserScripts on [GreasyFork](https://greasyfork.org/).

**Comment by matt873** [comment]
Is there any detailed tutorial documented somewhere like YouTube so that I watch it? Also, can I export bookmarks from Chrome mobile with this module which is only available for Chrome desktop?

**Comment by JingMatrix** [comment]
It is like Tampermonkey for mobile. You can learn how to use Tampermonkey first.
For the bookmark thing, I will take a look later to see if it is possible to implement.

**Comment by matt873** [comment]
> It is like Tampermonkey for mobile. You can learn how to use Tampermonkey first. For the bookmark thing, I will take a look later to see if it is possible to implement.

If it is possible to integrate the bookmark export feature, it will be really beneficial.
Nevertheless, mentioning Tampermonkey has clarified everything.

**Comment by MohamadBayz** [comment]
About that bookmark exporting I'm using this command to move my data from a browser to another maybe this could help you and if possible be implemented in ChromeXt
`Here are the Commands.
Firstly type su (For root permission)
move_chromium_data(){
if (( $# == 2 ));then
am force-stop $1
am force-stop $2
rm -rf /data/data/$2/*
cp -Rvf /data/data/$1/* /data/data/$2/
UGROUP=$(ls -al /data/data/ | grep $2 | awk '{ print $3 }')
chown -R $UGROUP:$UGROUP /data/data/$2
else
echo "Pass 2 args pls"
fi
}
After Pay attention here!
(Old browser package name to new browser package name)
move_chromium_data old.browser.package.name new.browser.package.name
Thanks pro  @frknkrc44 for command `
Note that i found this from another guy

**Comment by JingMatrix** [comment]
Bookmark exporting is implemented now.
