### ISSUE TITLE
Installed but unable to use

### ISSUE THREAD

**Issue by xiaowine** [JingMatrix/ChromeXt#57]
![image](https://github.com/JingMatrix/ChromeXt/assets/68009112/e524d3bb-1a2b-4d3c-9acb-941dc96cc3c3)
Edge 114.0.1823.41
[ChromeXt](https://github.com/JingMatrix/ChromeXt/actions/runs/5371799539)

**Comment by JingMatrix** [comment]
Sorry for the incovience, I forgot to test it on Edge browsers yesterday.
Now this bug is fixed.

**Comment by soulpursuit** [comment]
So is it now waiting for you to release a new version? Or do you still need Edge version apk? I downloaded the update from the Google Play Store

**Comment by xiaowine** [comment]
> So is it now waiting for you to release a new version? Or do you still need Edge version apk? I downloaded the update from the Google Play Store

It works fine

**Comment by soulpursuit** [comment]
> 您将 ChromeXt 更新为 [GitHub Action](https://github.com/JingMatrix/ChromeXt/actions/runs/5375496007) 中提供的 APK 或[更新发布页面](https://github.com/JingMatrix/ChromeXt/releases/tag/v3.3)中提供的 APK。
> 
> 每次我修复ChromeXt的错误时，都会在它之后构建新版本的APK。因此，最佳做法是从那里下载新版本的ChromeXt。`GitHub Action`

thank you i get it
