### ISSUE TITLE
How to use the app?

### ISSUE THREAD

**Issue by matt873** [JingMatrix/ChromeXt#59]
I searched for the user scripts option in Chrome after enabling the module but didn't find that. So how does this app work? How can I import/insert user scripts?

**Comment by matt873** [comment]
Thank you. I want to use it for just exporting bookmarks. How can I do that as I didn't find any userscripts for that in GreasyFork?

**Comment by JingMatrix** [comment]
Here is a [blog](https://www.askvg.com/tip-enable-hidden-secret-developer-options-menu-in-chrome-settings-in-mobile-phones/) with a video telling you how to find the `Developer options` menu.
It should be helpful for you.

**Comment by matt873** [comment]
Thank you so much for your kind help! I was able to successfully export bookmarks with a few clicks. Thank you so much again!
