### ISSUE TITLE
PatternSyntaxException causes Chrome crashed

### ISSUE THREAD

**Issue by commiyou** [JingMatrix/ChromeXt#64]
Chrome crashed, and the lsposed log shows
```
[ 2023-06-28T21:28:03.288    10153: 28117: 28117 I/LSPosed-Bridge  ]   Loading class org.matrix.chromext.MainHook
[ 2023-06-28T21:28:03.744    10153: 28018: 28157 I/LSPosed-Bridge  ] Crash unexpectedly: java.util.regex.PatternSyntaxException: Incorrectly nested parentheses in regexp pattern near index 41
\S*://(\S*\.)?investorschronicle\.co\.uk)
	at com.android.icu.util.regex.PatternNative.compileImpl(Native Method)
	at com.android.icu.util.regex.PatternNative.<init>(PatternNative.java:53)
	at com.android.icu.util.regex.PatternNative.create(PatternNative.java:49)
	at java.util.regex.Pattern.compile(Pattern.java:1446)
	at java.util.regex.Pattern.<init>(Pattern.java:1421)
	at java.util.regex.Pattern.compile(Pattern.java:972)
	at p.j.<init>(SourceFile:1)
	at a.a.g(Unknown Source:65)
	at r.l.a(SourceFile:65)
	at c.a.run(SourceFile:1)

```
the `investorschronicle` sinnpet comes from the userscript https://github.com/LegeBeker/bypass-paywalls-tampermonkey/blob/master/bypass-paywalls-tampermonkey.user.js

**Comment by commiyou** [comment]
Currently I have disabled ChromeXt. Is there any way to disable a userscript without starting Chrome?

**Comment by JingMatrix** [comment]
Enable ChromeXt, only open the front-end tab and close all others, then you can edit the script matching rules.

**Comment by JingMatrix** [comment]
Alternatively, edit the script matching rule, and then install it, it will override the original one.

You can install the script outside Chrome by choosing open it with ChromeXt.

**Comment by commiyou** [comment]
Thanks, tt's ok now. After I disabled chromeXT, I opened the chromext management page, then re-enabled chromeXt, and finally modified the user script. Previously, Chrome would crash when opened and could not be operated.

**Comment by JingMatrix** [comment]
Thanks for reporting this issue, it is fixed now.
You can install the updated ChromeXt from GitHub Action.
