### ISSUE TITLE
Edge crashes sometimes for unknown reasons

### ISSUE THREAD

**Issue by Sostay** [JingMatrix/ChromeXt#65]
这个版本Edge上的脚本终于能正常工作了，但是冷启动的时候有比较高的概率会显示崩溃页面，重启一次才能恢复
![d778f2ddf30289c0e51e5d608d4f47e](https://github.com/JingMatrix/ChromeXt/assets/6897274/cfe38857-ac51-4b58-90d2-7aceb033c8f7)

**Comment by JingMatrix** [comment]
有没有什么相关的 log 呢？你是从 GitHub Actions 上下载安装的 ChromeXt 吗？
下次崩溃的时候把相关 log 附上。

**Comment by Sostay** [comment]
> 有没有什么相关的 log 呢？你是从 GitHub Actions 上下载安装的 ChromeXt 吗？ 下次崩溃的时候把相关 log 附上。

移动版Edge的log在哪啊？不知道位置……

**Comment by JingMatrix** [comment]
If you find some related logs in your Xposed manager, such as LSPosed, post it here.

You can first try the lastest build from [GitHub Actions](https://github.com/JingMatrix/ChromeXt/actions/runs/5457431938), which might have already fixed the bug.

**Comment by Sostay** [comment]
> If you find some related logs in your Xposed manager, such as LSPosed, post it here.
> 
> You can first try the lastest build from [GitHub Actions](https://github.com/JingMatrix/ChromeXt/actions/runs/5457431938), which might have already fixed the bug.

[LSPosed_2023-07-06T18_58_55.808950.zip](https://github.com/JingMatrix/ChromeXt/files/11967713/LSPosed_2023-07-06T18_58_55.808950.zip)

[LSPosed_2023-07-06T18_59_28.250142.zip](https://github.com/JingMatrix/ChromeXt/files/11967716/LSPosed_2023-07-06T18_59_28.250142.zip)

**Comment by JingMatrix** [comment]
I found nothing abnormal in the logs.
By the way, your logs file is quite large.
Could you please clean your old logs before catching next possible crash?

For the page crashing, do you have a way to reproduce it surely?
Maybe it is only related to certain pages.
When a page crashed, are other pages functioning well?

**Comment by JingMatrix** [comment]
This issue will be re-open when you can re-produce it.

**Comment by Sostay** [comment]
> I found nothing abnormal in the logs. By the way, your logs file is quite large. Could you please clean your old logs before catching next possible crash?
> 
> For the page crashing, do you have a way to reproduce it surely? Maybe it is only related to certain pages. When a page crashed, are other pages functioning well?

![1688833927778](https://github.com/JingMatrix/ChromeXt/assets/6897274/ad86ffd1-57f1-430f-a222-cacbf31ce4bc)

![1688833927774](https://github.com/JingMatrix/ChromeXt/assets/6897274/ec894283-2a7f-4ae1-8cf0-2403a9e73d83)

**Comment by JingMatrix** [comment]
Install lastest ChromeXt from this [GitHub Actions link](https://github.com/JingMatrix/ChromeXt/actions/runs/5493393414), the problem should be then solved.
