### ISSUE TITLE
External Downloader

### ISSUE THREAD

**Issue by MuhammadBayiz** [JingMatrix/ChromeXt#68]
Is it possible to add an option for google chrome to use external Downloader (such as ADM or 1DM) instead of the it's downloader. Kiwi Browser has this feature where you can use an external Downloader in the browser.

**Comment by JingMatrix** [comment]
Which kinds of functions you want to have by using an external downloader?
Its speed or its managment of downloaded items?

**Comment by MohamadBayz** [comment]
Mostly because of the speed most of the time chrome is slow when it comes to downloading big files also external Downloaders has features that could ease how to manage downloaded contents for example it can sort different type of files to different directory

**Comment by JingMatrix** [comment]
For downloading speed, you can try to enable the flag `chrome://flags/#enable-parallel-downloading`.
If that is not faster, then I may try to consider implement this feature.

To sort your downloaded files, the Android file manager can do the job.

Personally, I prefer the original design of Chromium unless it has big or obvious drawback.
Also, I wish to save the module size for more important and necessary features.

**Comment by MohamadBayz** [comment]
I'll try it and see if it makes any improvements. If there's other features that's more important and haven't implemented yet then this one is a less  priority than the others.

**Comment by MohamadBayz** [comment]
I have been using Google chrome with that flag enabled for almost two week and for the first download it was fine but afterwards it all went down hill like today i have tried to download a 2GB file two times both times it stuck in around 30-60mb for an hour beside it made the phone lag i have an internet of 30Mbit/sec so to it would take some 10 minutes with an external Downloader but with Google chrome I've been waiting for an hour

**Comment by JingMatrix** [comment]
Chromium download is mostly handled by native `C++` codes, I didn't see a way to use external downloader with `ChromeXt`.

If anyone find a method in the future, please leave a message here.
