### ISSUE TITLE
Usersctipt bug

### ISSUE THREAD

**Issue by MohamadBayz** [JingMatrix/ChromeXt#72]
Hi! I use [IMDb Quick Search](https://greasyfork.org/en/scripts/427320-imdb-quick-search)  Usersctipt and After recent updates it started bugging like so
![Screenshot_20230715-142432_Chrome](https://github.com/JingMatrix/ChromeXt/assets/63660736/b53ddb95-dda1-4f80-94d6-00bd9f433280)

I don't think it's the UserScript's bug because the same version was working fine before.

**Comment by MohamadBayz** [comment]
This is the link i was trying it on
https://m.imdb.com/title/tt1190634/

When you scroll across the page more and more of buttons appears

**Comment by JingMatrix** [comment]
Thanks for keep using the beta release version, your reporting is valuable and helpful for the development of ChromeXt.

Now the bug is fixed, please try it from github action.
