### ISSUE TITLE
[Question] Can you support this application 

### ISSUE THREAD

**Issue by luxysiv** [JingMatrix/ChromeXt#74]
[This app](https://play.google.com/store/apps/details?id=org.triple.banana) has some nice futures like video player, by pass firewall... Can you support it?

**Comment by JingMatrix** [comment]
It was done just now. Check the GitHub Action for the lastest build.

**Comment by luxysiv** [comment]
Really? So amazing. Thanks so much. I hope you release on Github release soon

**Comment by JingMatrix** [comment]
I guess that, maybe you are not familiar with GitHub Action? You can download the lastest build now in this page: https://github.com/JingMatrix/ChromeXt/actions

If that is the case, I may suggest you to watch my [YouTube introducting video](https://www.youtube.com/watch?v=1Qm4dU-XnJM).

**Comment by luxysiv** [comment]
It works. So thanks again. This browser is so great but you make it greater
