### ISSUE TITLE
Duplicated downloading of Eruda Console

### ISSUE THREAD

**Issue by chengnan049** [JingMatrix/ChromeXt#77]
在 `Brave Beta 1.15.16 (Based on Chromium 115.0.5790.98)` 版本上会出现重复下载 Eruda 的情况，且下载失败，每次打开浏览器都会出现，设备为 Redmi Note 12 5G (sunstone) 环境为 MIUI 14 EEA Global，ChromeXt 为最新版本，上个版本没有出现该问题

**Comment by JingMatrix** [comment]
Tested on my phone, no such problem. Maybe you can try [the latest ChromeXt from GitHub Action](https://github.com/JingMatrix/ChromeXt/actions).
