### ISSUE TITLE
JingMatrix/LSPatch not working for Soul browser

### ISSUE THREAD

**Issue by luxysiv** [JingMatrix/ChromeXt#78]
I have read an issue said fully support Soul browser but I can't patch it on Manager. Please check it

**Comment by JingMatrix** [comment]
Can you post your patching logs here?

**Comment by JingMatrix** [comment]
Currently, for Soul browser, [the original LSPatch](https://github.com/LSPosed/LSPatch) project works.
I will fix [JingMatrix/LSPatch](https://github.com/JingMatrix/LSPatch) in the future.
This is not a bug of ChromeXt, so I close it here.

**Comment by JingMatrix** [comment]
The related bug in `JingMatrix/LSPatch`, you should be able to use it.

Note: if you patch the `Soul Browser` installed from google play using the manager app, you need [Shizuku](https://github.com/RikkaApps/Shizuku) to help you install the patched split APKs.
