### ISSUE TITLE
能否添加开关，关闭“将右侧返回手势去掉”这个feature

### ISSUE THREAD

**Issue by chuwza** [JingMatrix/ChromeXt#85]
大佬你好，能否添加一个开关，来将这个feature关掉呢？个人认为右撇子、习惯用右侧全面屏返回手势的人还是蛮多的

**Comment by JingMatrix** [comment]
有这个开关的，看  [README](https://github.com/JingMatrix/ChromeXt#solution-of-system-gesture-conflicts).
