### ISSUE TITLE
LSPatched Chromium based browsers cannot login Google Account

### ISSUE THREAD

**Issue by mingCONG1** [JingMatrix/ChromeXt#89]
我用LSPatch嵌入了模块打开谷歌浏览器后登陆不了账号是什么原因呢

**Comment by JingMatrix** [comment]
我以前有注意到这个现象，但是没有成功绕过这一限制。
它应该是谷歌的安全验证机制，大概原理是验证了应用签名吧。因为这部分代码是不开源的，所以目前我也没有办法。

**Comment by JingMatrix** [comment]
It is not easy to bypass `GoogleSignatureVerifier` of SafeNet.
Also, it might cause some secutity concern of the browser or incur blames from `Google`.

Hence, I will simply leave this problem as `won't fix`.

**Comment by Violet-Vibes** [comment]
Sorry for necroing this issue, but would it be possible to use the implementation of [microg/gmscore](https://github.com/ReVanced/GmsCore) from revanced?
