### ISSUE TITLE
[Bug] ChromeXt v3.6 front-end not showing installed UserScripts

### ISSUE THREAD

**Issue by eisklwksjs** [JingMatrix/ChromeXt#91]
I patched Brave browser with lspatch from the github actions, installed it; Searched for usersctipts on greasyfork, clicked on "install this script" and headed to github.io frontend mentioned in the readme page, but its empty no matter what script i install; headed to developer options and cleared chromext and console data and tried again with no luck. Tried different frontends and still the problem persists.......i couldn't figure out what went wrong

I gave all the permissions....
![Screenshot_20230812-211338_Permission_controller](https://github.com/JingMatrix/ChromeXt/assets/90270441/6a8824f8-f0c9-4aa1-8b50-5c953bc84a10)
![Screenshot_20230812-212014_Brave](https://github.com/JingMatrix/ChromeXt/assets/90270441/4a28f03b-9e5c-4454-a56e-c987e83484bb)
![Screenshot_20230812-212032_Brave](https://github.com/JingMatrix/ChromeXt/assets/90270441/b89b5bc5-5387-41df-97ec-363ce2e736e4)

**Comment by JingMatrix** [comment]
There was a bug when I released ChromeXt v3.6 two days ago.
I fixed it yesterday.
Can you please download ChromeXt, and re-patch it?
The problem is not in LSPatch, neither in Brave, is in ChromeXt.
Sorry for the inconvience.

**Comment by JingMatrix** [comment]
Wait, my judgement was wrong. I will fix it soon.

**Comment by eisklwksjs** [comment]
Thank you

**Comment by JingMatrix** [comment]
Now it is fixed, you can download ChromeXt from GitHub Actions.
When I was developing ChromeXt, I forget to test scripts installation (I only tested installation using Eruda).

**Comment by eisklwksjs** [comment]
👍
