### ISSUE TITLE
Is DuckDuckGo browser supported?

### ISSUE THREAD

**Issue by DarkSkull91** [JingMatrix/ChromeXt#95]
Hello everyone! I use DuckDuckGo browser as my default browser, is it supported? If not can you add the compatibility?

Thanks

**Comment by JingMatrix** [comment]
Yes, it is supported as a WebView browser.
I update the codes a bit to improve user experience for WebView browser.
Hence, remember to use ChromeXt from GitHub Actions, as said in the README.
