### ISSUE TITLE
Support @require for non-standard library scripts

### ISSUE THREAD

**Issue by wowotaa** [JingMatrix/ChromeXt#97]
图片类的聚合脚本和下载脚本都不能生效使用

**Comment by JingMatrix** [comment]
Which ones are not working? Please be polite and precise when you describe them.

**Comment by wowotaa** [comment]
大神这两个脚本食用不了，能解决一下吗？
 Picviewer CE+
脚本地址 https://greasyfork.org/scripts/24204-picviewer-ce/code/Picviewer%20CE+.user.js

图聚合展示by xhua
脚本地址 https://sleazyfork.org/scripts/442098-%E5%9B%BE%E8%81%9A%E5%90%88%E5%B1%95%E7%A4%BAby-xhua/code/%E5%9B%BE%E8%81%9A%E5%90%88%E5%B1%95%E7%A4%BAby%20xhua.user.js

**Comment by JingMatrix** [comment]
Two related bugs to fix:
1. Contexts for `@require` JavaScripts are isolated and hence not accessible to the UserScript.
2. HTTP response with `gzip` content type are not deflated before `onload` is called.

**Comment by JingMatrix** [comment]
Now the bugs are fixed.
Please try the latest built form [GitHub Actions](https://github.com/JingMatrix/ChromeXt/actions).
